Decathlon/vitamin-web

.github/semantic.yml
.github/workflows/sonarchecks.yml
sonar-project.properties

Pending request approval on Github side to generate a token on sonarcloud
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
Please check the type of change your PR introduces:
- Feature
- Currently there is no check at all.
Issue Number: Close #11  
- This github actions will be triggered on every push and PR in order to check code quality.

feat: Setup sonarcloud to check quality

---

README.md

Add sonarcloud quality gate badge link into readme file.
- Documentation content changes
Add sonarcloud quality gate badge link into readme file.
No badge are displayed.
Issue Number: Close #13 
❤️ Thank you!

chore: Readme update with sonarcloud badge

---

README.md

Please check the type of change your PR introduces:
Fix URL for the **last commit** badge.
Current URL redirect to a 404 GitHub page.
Issue Number: N/A
New URL is able to list all latest commit according to the default configured branch name.
It could be `master` or `main` or whatever.
Hope you will find this useful!
❤️ Thank you!

docs: update README.md file

---

packages/css/.storybook/main.js
packages/css/package.json
packages/css/postcss.config.js
packages/css/src/components/buttons.css
packages/css/src/design-tokens/colors.css
packages/css/src/design-tokens/spacings.css
packages/css/tailwind.config.js
yarn.lock

Please check the type of change your PR introduces:
- Refactoring (no functional changes, no api changes)
Issue Number: #24 
- No
❤️ Thank you!

refactor(css): migrate to TailwindCSS with @apply

---

.github/workflows/build-main.yml
.github/workflows/build-pr.yml

CI managed thanks to Github actions. 
Basic steps for now, no deploy yet. 
It will ensure that the basic checks are OK. 
- install dependencies
- build 
- lint
- test
Issue Number: #8

ci: init ci for PR and main build

---

.github/CODEOWNERS
.github/workflows/build-main.yml
README.md
packages/showcases/css/.storybook/addons/viewports.json
packages/sources/css/postcss.config.js
packages/sources/css/src/components/button/package.json
packages/sources/css/src/shared/postcss-config/package.json
packages/sources/css/src/shared/postcss-config/postcss.config.js
packages/sources/css/src/shared/tailwind-config/package.json
sonar-project.properties
yarn.lock

Hotfix this: https://github.com/Decathlon/vitamin-web/actions/runs/477293693/workflow
- No

fix: build main branch

---

package.json
packages/sources/css/.stylelintrc.json
packages/sources/css/package.json
packages/sources/css/src/components/button/package.json
packages/sources/css/src/components/button/src/index.css
packages/sources/css/src/shared/design-tokens/src/colors.css
packages/sources/css/src/shared/design-tokens/src/typography.css
yarn.lock

fix: stylelint errors

---

.github/workflows/build-pr.yml
packages/showcases/css/sonar-project.properties
packages/sources/css/sonar-project.properties
packages/sources/css/src/components/button/sonar-project.properties
packages/sources/css/src/shared/design-tokens/sonar-project.properties
packages/sources/css/src/shared/postcss-config/sonar-project.properties
packages/sources/css/src/shared/tailwind-config/sonar-project.properties
packages/sources/css/src/shared/utilities/sonar-project.properties

This pull request set things up for sonar monorepo strategy.
- No
fix #35 
❤️ Thank you!

ci: Create sonar project properties for showcases

---

.github/workflows/build-main.yml

Fix sonar setup not used by main build

fix: build-main

---

.github/workflows/build-main.yml

Should fix the weird bug of https://github.com/Decathlon/vitamin-web/runs/1696610267?check_suite_focus=true 
See https://github.com/storybookjs/storybook-deployer/issues/86 for more info

ci: fix deploy storybook

---

package.json
packages/showcases/css/package.json
packages/sources/css/package.json
packages/sources/css/src/shared/design-tokens/package.json
packages/sources/css/src/shared/design-tokens/src/typography.css
packages/sources/css/src/shared/utilities/package.json
yarn.lock

Fixes this bug (#47) and upgrade Storybook packages.
- No

fix: font-family on Typography CSS styles

---

README.md

docs: delete sonarcloud badge

---

README.md
packages/showcases/css/README.md
packages/sources/css/README.md
packages/sources/css/config/postcss/README.md
packages/sources/css/config/tailwind/README.md
packages/sources/css/src/components/button/README.md
packages/sources/css/src/components/button/package.json
packages/sources/css/src/design-tokens/README.md
packages/sources/css/src/utilities/README.md
packages/sources/css/src/utilities/package.json

docs: add packages part in README

---

.github/workflows/build-main.yml
.github/workflows/build-pr.yml

fix: build for Pull Requests

---

.github/workflows/build-pr.yml

Simple fix for github action to have the sonar check on PR.
- Functionally, no
- Technically, PR are checked against the merge (like github do with pull_request event) and not against the head itself. 
Just a technical PR.
❤️ Thank you!

chore: Fix sonar to have sonar check on PR

---

.github/workflows/build-pr.yml

disable sonar on PR
- Yes
- No
❤️ Thank you!

chore: Security on pull request target

---

.github/workflows/build-main.yml

fix: build main

---

packages/sources/css/config/postcss/postcss.config.js
packages/sources/css/config/tailwind/tailwind.config.js

Some refactoring thanks to suggestions from @LionelSpanneut & @Anthony-dkt, thanks a lot!
- we don't need `!important` in each `@vtmn/css` instructions
- it will be better to have `min` and `max` in each `@media` queries
- we have duplicated blocks generated by PostCSS for the same classes. So it will be better to merge them.
- No

refactor: tailwindcss & postcss configurations

---

CONTRIBUTING.md
README.md
packages/showcases/css/README.md
packages/showcases/react/README.md
packages/showcases/web-components/README.md
packages/sources/css/README.md
packages/sources/css/config/postcss/README.md
packages/sources/css/config/tailwind/README.md
packages/sources/css/package.json
packages/sources/css/src/components/button/README.md
packages/sources/css/src/components/button/package.json
packages/sources/css/src/components/text-input/README.md
packages/sources/css/src/components/text-input/package.json
packages/sources/css/src/design-tokens/README.md
packages/sources/css/src/design-tokens/package.json
packages/sources/css/src/utilities/README.md
packages/sources/css/src/utilities/package.json
packages/sources/react/README.md
packages/sources/react/package.json
packages/sources/web-components/README.md

Enhance the documentation and showcases.
The goal is to onboard easily every developer that will consume and/or contribute Vitamin web libraries with complete README files.
**To help you review, browse README files here: https://github.com/Decathlon/vitamin-web/tree/docs/enhance-dx**
- No
Thanks!

docs: enhance Developer eXperience with complete README files

---

.github/workflows/build-pr.yml
package.json

Build the storybooks in CI to ensure that they are buildable before merging to main branch. 
- No
❤️ Thank you!

ci: ensure storybooks are buildable in PR

---

packages/sources/css/config/tailwind/tailwind.config.js
packages/sources/css/src/components/button/src/index.css

Fix: https://github.com/Decathlon/vitamin-web/issues/29#issuecomment-786549770
- No
❤️ Thank you!

refactor(@vtmn/css): delete line-height with units

---

CONTRIBUTORS.md

Following commit `14df58d` introduced the `CONTRIBUTORS.md` file which contains a wrong GitHub URL profile.
Hope you find this useful and thank you for the review!
- No

docs(contributors): update GitHub URL profile

---

packages/sources/css/config/postcss/package.json
packages/sources/css/config/postcss/postcss-core.config.js
packages/sources/css/src/design-tokens/package.json
yarn.lock

Close #141.
Unfortunately, too difficult to use Amazon Style Dictionary (because we need to have relative units, no units for line-heights and support of base 16 & base 10...)
So, in order to resolve this issue I've used https://github.com/arpadHegedus/postcss-css-var-to-sass-var and I've forked it to create https://github.com/lauthieb/postcss-css-var-to-less-var, then I've published it on NPM.
- No
❤️ Thank you!

feat(@vtmn/css-design-tokens): generate .scss & .less outputs

---

packages/showcases/svelte/stories/components/VtmnTextInput/VtmnTextInput.stories.js
packages/sources/css/src/components/text-input/src/index.css
packages/sources/svelte/rollup.config.js
packages/sources/svelte/src/components/VtmnTextInput.svelte

Initialize the svelte version for text-input.
Needed to add Roboto-Condensed on CSS package of text-input. 
See #5

feat(text-input): initialize Svelte

---

CONTRIBUTING.md

I changed the showcase URLs written in the 'CONTRIBUTING.md' file because they were mismatching the actual ones.
- No
❤️ Thank you!

fix(doc): change localhost showcase URLs with actual ones

---

packages/showcases/css/stories/components/text-input/examples/default.html
packages/showcases/css/stories/components/text-input/examples/disabled.html
packages/showcases/css/stories/components/text-input/examples/error.html
packages/showcases/css/stories/components/text-input/examples/multiline.html
packages/showcases/css/stories/components/text-input/examples/valid.html
packages/sources/css/src/components/text-input/src/index.css

- Add vtmn class for text input label
- Reduce text input top margin to match figma guildelines
- Change error message color to black
- Change default error message
- No
❤️ Thank you!

feat(vtmn-text-input): text input improvements

---

packages/showcases/css/.storybook/main.js

This pull request fix the issue #142  
- No
See ya !

fix(docs): avoid linting HTML examples

---

packages/showcases/css/stories/components/toggle/examples/medium.html
packages/sources/css/src/components/toggle/src/index.css

refactor(@vtmn/css-toggle): change the check svg

---

packages/sources/css/src/components/button/src/index.css

Designers has decided to change Roboto Condensed font family for buttons to Roboto.
- No
❤️ Thank you!

refactor(@vtmn/css-button): change font-family

---

packages/showcases/react/package.json
packages/showcases/react/stories/components/VtmnButton/VtmnButton.stories.tsx
packages/showcases/react/stories/components/VtmnTextInput/VtmnTextInput.stories.tsx
packages/showcases/svelte/stories/components/VtmnTextInput/VtmnTextInput.stories.js
packages/sources/react/src/components/VtmnTextInput/VtmnTextInput.tsx
packages/sources/react/src/components/VtmnTextInput/index.ts
packages/sources/react/src/components/VtmnTextInput/types.ts
packages/sources/react/src/index.ts
yarn.lock

Text Input feature, react part. (issue #5)
- No
This PR is ✅, i'm waiting for you advices.
❤️ Thank you!

feat(@vtmn/react): add text input component

---

packages/showcases/css/stories/components/link/link.stories.js

- In the showcase story part, variable are now set with the actual story variable used.
- 
- No
❤️ Thank you!

fix(@vtmn/css-link): fix variable error in the link showcase part

---

.husky/commit-msg
.husky/pre-commit
package.json

close #284 
- No
❤️ Thank you!

chore(commitlint): fix bug

---

.gitignore
packages/sources/icons/package.json
packages/sources/icons/src/scripts/add-sprite-declaration.js

Add icons sprite Typescript declaration file at build time. Preventing svelte validate to yield warning regarding missing declaration file.
- No
❤️ Thank you!

feat(vtmn-icons): add sprite type declaration

---

packages/showcases/css/stories/components/text-input/examples/disabled.html
packages/showcases/css/stories/components/text-input/examples/error.html
packages/showcases/css/stories/components/text-input/examples/valid.html
packages/sources/css/src/components/text-input/src/index.css

docs(@vtmn/css-text-input): delete broken external svg embedded stories

---

README.md
packages/sources/css/src/components/button/README.md
packages/sources/css/src/components/checkbox/README.md
packages/sources/css/src/components/link/README.md
packages/sources/css/src/components/text-input/README.md
packages/sources/css/src/components/toggle/README.md
packages/sources/css/src/utilities/README.md

- Rename links with correct address
- No
❤️ Thank you!

docs: rename links

---

packages/showcases/css/stories/components/button/examples/conversion.html
packages/showcases/css/stories/components/button/examples/ghost.html
packages/showcases/css/stories/components/button/examples/overview.html
packages/showcases/css/stories/components/button/examples/primary-reversed.html
packages/showcases/css/stories/components/button/examples/primary.html
packages/showcases/css/stories/components/button/examples/secondary-reversed.html
packages/showcases/css/stories/components/button/examples/secondary.html
packages/sources/css/src/components/button/src/index.css

refactor(@vtmn/css-button): stretched sizes

---

packages/showcases/css/stories/components/link/examples/large.html
packages/showcases/css/stories/components/link/examples/medium.html
packages/showcases/css/stories/components/link/examples/overview.html
packages/showcases/css/stories/components/link/examples/small.html
packages/sources/css/src/components/link/src/index.css

- Inline and standalone links now have a different border style
- Style corrections
- No
❤️ Thank you!

fix(@vtmn/css-link): refacto standalone + inline links styles

---

packages/showcases/css/stories/components/button/examples/conversion.html
packages/showcases/css/stories/components/button/examples/ghost.html
packages/showcases/css/stories/components/button/examples/overview.html
packages/showcases/css/stories/components/button/examples/primary-reversed.html
packages/showcases/css/stories/components/button/examples/primary.html
packages/showcases/css/stories/components/button/examples/secondary-reversed.html
packages/showcases/css/stories/components/button/examples/secondary.html

- Add accessibility aria-label prop on icon-only buttons
- Replace search icon by add icon
- Re-work of the overview showcase (was similar to primary variant)
- No
❤️ Thank you!

refactor(@vtmn/css-button): rework showcase

---

packages/sources/css/config/tailwind/tailwind.config.js
packages/sources/css/package.json

The goal of this PR is to add alternative css bundles which does not include Tailwind's normalizing rules.
These bundles are needed when you want to embed your product inside another one and avoid overriding the legacy rules.
- No

ci(sources/css): add unreset bundles' build

---

packages/showcases/web-components/stories/components/vtmn-text-input/vtmn-text-input.stories.tsx
packages/showcases/web-components/stories/components/vtmn-toggle/vtmn-toggle.stories.tsx
packages/sources/web-components/src/components.d.ts
packages/sources/web-components/src/components/vtmn-text-input/README.md
packages/sources/web-components/src/components/vtmn-text-input/vtmn-text-input.tsx
packages/sources/web-components/src/components/vtmn-toggle/README.md
packages/sources/web-components/src/components/vtmn-toggle/vtmn-toggle.tsx

- Rename id attribute in components
- No
❤️ Thank you!

fix(@vtmn/web-components): change public reserved name of id attribute for toggle and text input components

---

packages/showcases/css/stories/components/checkbox/checkbox.stories.js
packages/showcases/css/stories/components/checkbox/examples/indeterminate.html
packages/showcases/css/stories/components/checkbox/examples/overview.html
packages/sources/css/src/components/checkbox/src/index.css

- Darker border for unselected state
- Decrease radius
- Better alignment for label and check icon
- Add indeterminate style + showcase
- No
❤️ Thank you @z28kmorl !

fix(@vtmn/css-checkbox): bug fixes + improvements

---

packages/showcases/vue/stories/VtmnCheckbox/VtmnCheckbox.stories.js
packages/sources/css/src/components/checkbox/src/index.css
packages/sources/vue/src/components/VtmnCheckbox/VtmnCheckbox.vue
packages/sources/vue/src/components/VtmnCheckbox/index.ts

- Add checkbox component for Vue 
- No
❤️ Thank you!

feat(@vtmn/vue): add checkbox component

---

packages/sources/css/src/components/text-input/src/index.css

- Enable to resize tje textarea
- No
❤️ Thank you!

fix(@vtmn/css-textinput): add resize property

---

packages/showcases/core/src/components/VtmnLink.csf.js
packages/showcases/web-components/stories/components/vtmn-link/vtmn-link.stories.tsx
packages/sources/react/src/components/VtmnLink/VtmnLink.tsx
packages/sources/svelte/src/components/VtmnLink.svelte
packages/sources/web-components/src/components.d.ts
packages/sources/web-components/src/components/vtmn-link/README.md
packages/sources/web-components/src/components/vtmn-link/vtmn-link.tsx

- Rename attributes to have consistent structure
- Add iconAlong prop to display icon when standalone
- No
❤️ Thank you!

refactor(@vtmn/svelte & @vtmn/react & @vtmn/web-components): rename attribute + add logic for icon

---

packages/showcases/web-components/.storybook/preview.js
packages/showcases/web-components/stories/components/vtmn-text-input/vtmn-text-input.stories.tsx
packages/sources/web-components/src/components.d.ts
packages/sources/web-components/src/components/vtmn-text-input/README.md
packages/sources/web-components/src/components/vtmn-text-input/vtmn-text-input.tsx

- Rename attribute to have consistent architecture
- split state attribute into two booleans (as react part)
- Textarea can't be in valid state
- Textarea has no helper text, only an error one
- No
❤️ Thank you!

refactor(@vtmn/web-components): rename attribute + add icon select for text input

---

packages/showcases/vue/.storybook/preview.js
packages/showcases/vue/stories/VtmnTextInput/VtmnTextInput.stories.js
packages/sources/vue/src/components/VtmnTextInput/VtmnTextInput.vue
packages/sources/vue/src/components/VtmnTextInput/index.ts
packages/sources/vue/src/components/index.ts

- Add text input component in Vue
- No
❤️ Thank you!

feat(@vtmn/vue): add text input component

---

packages/showcases/svelte/.storybook/preview.js
packages/showcases/svelte/package.json
packages/showcases/svelte/stories/components/VtmnButton/VtmnButton.stories.js
packages/sources/svelte/README.md
packages/sources/svelte/package.json
packages/sources/svelte/src/components/VtmnButton.svelte

feat(@vtmn/svelte): add icons in button component

---

packages/showcases/vue/stories/VtmnButton/VtmnButton.stories.js
packages/sources/vue/README.md
packages/sources/vue/package.json
packages/sources/vue/src/components/VtmnButton/VtmnButton.vue

feat(@vtmn/vue): add icons in button component

---

packages/showcases/vue/stories/VtmnToggle/VtmnToggle.stories.js
packages/sources/vue/src/components/VtmnToggle/VtmnToggle.vue
packages/sources/vue/src/components/VtmnToggle/index.ts

- Add toggle component for Vue
- No
❤️ Thank you!

feat(@vtmn/vue): add toggle component

---

packages/showcases/react/stories/components/VtmnCheckbox/VtmnCheckbox.stories.tsx
packages/sources/react/src/components/VtmnCheckbox/VtmnCheckbox.tsx
packages/sources/react/src/components/VtmnCheckbox/index.ts
packages/sources/react/src/index.ts

- Add checkbox react component
- No
❤️ Thank you!

feat(@vtmn/react): add checkbox component

---

packages/showcases/css/stories/components/text-input/examples/disabled.html
packages/showcases/css/stories/components/text-input/examples/error.html
packages/showcases/css/stories/components/text-input/examples/multiline.html
packages/showcases/css/stories/components/text-input/examples/overview.html
packages/showcases/css/stories/components/text-input/examples/valid.html
packages/sources/css/src/components/text-input/src/index.css

- Remove valid state for textarea
- Remove hover effect for textarea
- Remove helper text for textarea
- Set minimum width and height for textarea
- NO
❤️ Thank you!

feat(@vtmn/css): improvements (text input)

---

packages/showcases/react/stories/components/VtmnTextInput/VtmnTextInput.stories.tsx
packages/showcases/svelte/stories/components/VtmnTextInput/VtmnTextInput.stories.js
packages/sources/react/src/components/VtmnTextInput/VtmnTextInput.tsx
packages/sources/svelte/src/components/VtmnTextInput.svelte
packages/sources/web-components/src/components.d.ts
packages/sources/web-components/src/components/vtmn-checkbox/README.md
packages/sources/web-components/src/components/vtmn-checkbox/vtmn-checkbox.tsx
packages/sources/web-components/src/components/vtmn-radio/README.md
packages/sources/web-components/src/components/vtmn-radio/vtmn-radio.tsx
packages/sources/web-components/src/components/vtmn-toggle/README.md
packages/sources/web-components/src/components/vtmn-toggle/vtmn-toggle.tsx

- Rename attributes to have a consistent structure
- No
❤️ Thank you!

refactor(@vtmn/web-components @vtmn/svelte @vtmn/react): renaming 

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTORS.md

- [ x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [ x] Make sure you are making a pull request against the **main branch** (left side).
- [ x] Check the commit's or even all commits' message styles matches our requested structure.
- [ x] Check your code additions will fail neither code linting checks nor unit test.
- Add a new amazing contributor
- Change PR template
- No
❤️ Thank you!

docs(global): update doc

---

.github/CODEOWNERS

Add the CODEOWNERS file.
- No
❤️ Thank you!

chore: code owners

---

packages/sources/css/src/components/badge/src/index.css
packages/sources/css/src/components/button/src/index.css
packages/sources/css/src/components/checkbox/src/index.css
packages/sources/css/src/components/link/src/index.css
packages/sources/css/src/components/radio-button/src/index.css
packages/sources/css/src/components/text-input/src/index.css
packages/sources/css/src/components/toggle/src/index.css
packages/sources/css/src/design-tokens/src/index.css
packages/sources/css/src/design-tokens/src/opacities.css
packages/sources/css/src/design-tokens/src/states.css
packages/sources/css/src/utilities/src/index.css

- The opacity for the disable state of input element is a variable
- No
❤️ Thank you!

feat(@vtmn/css): add variable for disabled state opacity

---

packages/showcases/core/csf/components/VtmnTextInput.csf.js
packages/sources/react/src/components/VtmnTextInput/VtmnTextInput.tsx
packages/sources/svelte/src/components/VtmnLink.svelte
packages/sources/svelte/src/components/VtmnTextInput.svelte
packages/sources/vue/src/components/VtmnLink/VtmnLink.vue
packages/sources/vue/src/components/VtmnTextInput/VtmnTextInput.vue
packages/sources/web-components/src/components/vtmn-text-input/vtmn-text-input.tsx

- Add multiline variant of text input in svelte
- Add icon fot text input in svlete
- Remove valid state for multiline
- Remove Helper text for multiline, the multiline can only display an error message
- Add multiline variant of text input in react
- No
❤️ Thank you!

feat(@vtmn/react @vtmn/vue @vtmn/svelte): correct multiline states and helper texts

---

packages/sources/css/src/components/text-input/src/index.css

Close #461 
- No
❤️ Thank you!

refactor(@vtmn/css-text-input): fix appearance

---

packages/sources/react/src/components/VtmnIcon/VtmnIcon.tsx

docs(@vtmn/react): rename icon component to vtmn icon in documentation

---

packages/showcases/react/stories/components/VtmnBadge/VtmnBadge.stories.tsx
packages/sources/react/src/components/VtmnBadge/VtmnBadge.tsx
packages/sources/react/src/components/VtmnBadge/index.ts
packages/sources/react/src/components/VtmnBadge/types.ts
packages/sources/react/src/index.ts
packages/sources/web-components/src/components/vtmn-badge/vtmn-badge.tsx

feat(@vtmn/web-components): add badge component

---

packages/sources/css/src/components/button/src/index.css

- Use transform to align visually the icons
- No
❤️ Thank you!

fix(@vtmn/css): better icon alignment for buttons

---

.github/workflows/build-main.yml
.github/workflows/build-pr.yml
README.md
packages/showcases/css/stories/components/tooltip/examples/overview.html
packages/showcases/css/stories/components/tooltip/tooltip.stories.js
packages/sources/css/src/components/tooltip/README.md
packages/sources/css/src/components/tooltip/package.json
packages/sources/css/src/components/tooltip/postcss.config.js
packages/sources/css/src/components/tooltip/sonar-project.properties
packages/sources/css/src/components/tooltip/src/index.css
packages/sources/css/src/design-tokens/src/index.css
packages/sources/css/src/design-tokens/src/shadows.css
packages/sources/css/src/index.css
packages/sources/icons/src/templates/css.hbs

feat(@vtmn/css): add tooltip component

---

packages/sources/react/src/components/VtmnCheckbox/VtmnCheckbox.tsx
packages/sources/react/src/components/VtmnRadioButton/VtmnRadioButton.tsx
packages/sources/react/src/components/VtmnToggle/VtmnToggle.tsx

- It is now possible de to check a toggle and a checkbox component by clicking on it
- No
❤️ Thank you!

fix(@vtmn/react): fix the checked state

---

packages/sources/css/src/components/select/src/index.css

- Change the icon from display from the label to the select container for more independence
- No
❤️ Thank you!

refactor(@vtmn/css-select): update ::after icon

---

packages/showcases/css/stories/components/popover/examples/overview.html

- Change showcase for a better display for mobile devices
- No
❤️ Thank you!

fix(@vtmn/css-popover): change showcase for a better mobile experience

---

packages/showcases/css/stories/components/tooltip/examples/overview.html
packages/sources/css/src/components/popover/src/index.css
packages/sources/css/src/components/tooltip/src/index.css
packages/sources/css/src/design-tokens/src/animations.css
packages/sources/css/src/design-tokens/src/index.css

- Better showcase display for tooltip
- Add animations as variable on popover and tooltip
- Add shadow variable on popover
- Add a media query to prevent hover on mobile devices and replace it by a focus event
- No
❤️ Thank you!

feat(@vtmn/css-popover & @vtmn/css-tooltip): change showcase for a better global experience

---

packages/showcases/css/.storybook/preview-head.html
packages/showcases/web-components/.storybook/preview-body.html
packages/showcases/web-components/.storybook/preview-head.html
packages/showcases/web-components/.storybook/preview.js
packages/showcases/web-components/package.json
packages/sources/web-components/README.md
packages/sources/web-components/package.json
packages/sources/web-components/src/components/vtmn-badge/vtmn-badge.pcss
packages/sources/web-components/src/components/vtmn-button/vtmn-button.pcss
packages/sources/web-components/src/components/vtmn-checkbox/vtmn-checkbox.pcss
packages/sources/web-components/src/components/vtmn-link/vtmn-link.pcss
packages/sources/web-components/src/components/vtmn-radio-button/vtmn-radio-button.pcss
packages/sources/web-components/src/components/vtmn-text-input/vtmn-text-input.pcss
packages/sources/web-components/src/components/vtmn-toggle/vtmn-toggle.pcss
packages/sources/web-components/stencil.config.ts

Allow theming for web components.
Thanks a lot @jleveugle for your help.
- Yes (documented via `README.md` + `dependencies` for `@vtmn/css-design-tokens`
❤️ Thank you!

refactor(@vtmn/web-components): allow theming for Web Components

---

packages/sources/css/src/components/button/src/index.css
packages/sources/css/src/components/link/src/index.css
packages/sources/css/src/design-tokens/src/base-colors.css
packages/sources/css/src/design-tokens/src/themes/core-dark.css
packages/sources/css/src/design-tokens/src/themes/core-light.css
packages/sources/css/src/design-tokens/src/themes/default.css

refactor(@vtmn/css): design changes

---

packages/showcases/css/.storybook/preview-head.html
packages/showcases/react/.storybook/preview-head.html
packages/showcases/web-components/.storybook/preview-head.html
yarn.lock

Fixes the code colors in showcases.
No
❤️ Thank you!

fix(showcases): code text is black on black background in light mode #560

---

packages/sources/css/src/components/button/src/index.css

refactor(@vtmn/css-button): primary reversed on hover and active

---

packages/sources/css/src/components/button/src/index.css

refactor(@vtmn/css-button): add multiline exception

---

.github/ISSUE_TEMPLATE/component_request.md

- Add a template for creating component issues faster
- No
❤️ Thank you!

feat(@vtmn): add component to create component issue faster

---

packages/sources/css/src/components/button/src/index.css

refactor(@vtmn/css-button): fix focus-visible box-shadows

---

packages/sources/css/src/components/modal/src/index.css

Before:
After:
- No
❤️ Thank you!

refactor(@vtmn/css-modal): imports

---

.gitignore
.vscode/extensions.json
packages/showcases/css/.storybook/main.js
yarn.lock

chore: add VSCode recommended extensions

---

packages/showcases/css/stories/guidelines/colors/colors.stories.mdx
packages/showcases/css/stories/guidelines/layout/layout.stories.mdx
packages/showcases/css/stories/guidelines/theming/theming.stories.mdx
packages/showcases/css/stories/introduction.stories.mdx
packages/showcases/icons/stories/overview.stories.mdx
packages/sources/css/README.md

- chore: migrate storybook
- Yes
- No
❤️ Thank you!

chore(storybook): fix deprecated content

---

packages/showcases/core/package.json
packages/sources/css/config/postcss/package.json
packages/sources/css/config/tailwind/package.json
packages/sources/css/src/components/alert/src/index.css
packages/sources/css/src/components/badge/package.json
packages/sources/css/src/components/badge/src/index.css
packages/sources/css/src/components/button/src/index.css
packages/sources/css/src/components/checkbox/src/index.css
packages/sources/css/src/components/link/src/index.css
packages/sources/css/src/components/modal/src/index.css
packages/sources/css/src/components/popover/src/index.css
packages/sources/css/src/components/progressbar/build.js
packages/sources/css/src/components/progressbar/package.json
packages/sources/css/src/components/progressbar/src/index.css
packages/sources/css/src/components/radio-button/src/index.css
packages/sources/css/src/components/rating/src/index.css
packages/sources/css/src/components/select/src/index.css
packages/sources/css/src/components/skeleton/src/index.css
packages/sources/css/src/components/snackbar/src/index.css
packages/sources/css/src/components/text-input/src/index.css
packages/sources/css/src/components/toast/src/index.css
packages/sources/css/src/components/toggle/src/index.css
packages/sources/css/src/components/tooltip/src/index.css
packages/sources/css/src/utilities/src/typography.css

refactor: clean CSS imports & package.json dependencies

---

packages/showcases/css/stories/components/snackbar/examples/demo.runscript.js

- Resolve bug where the button of the snackbar wasn't properly working in the demo showcase
- No
❤️ Thank you!

fix(@vtmn/css-snackbar): fix html snackbar button

---

packages/showcases/react/.storybook/manager.js
packages/showcases/react/.storybook/preview.js
packages/showcases/svelte/.storybook/manager.js
packages/showcases/svelte/.storybook/preview.js
packages/showcases/vue/.storybook/manager.js
packages/showcases/vue/.storybook/preview.js
packages/showcases/web-components/.storybook/manager.js
packages/showcases/web-components/.storybook/preview.js

- Storybook control pane is now at the bottom for react, wc, svelte and vue.
- Control panel now have 2 new columns for description and default value 
- No
❤️ Thank you!

feat(@vtmn/react @vtmn/vue @vtmn/web-components @vtmn/svelte): control panel

---

packages/showcases/css/.storybook/preview-body.html
packages/showcases/css/.storybook/preview-head.html
packages/showcases/react/.storybook/preview-body.html
packages/showcases/react/.storybook/preview-head.html
packages/showcases/web-components/.storybook/preview-body.html
packages/showcases/web-components/.storybook/preview-head.html

- Add report form in storybook toolbar
- No
❤️ Thank you!

feat(@vtmn/web-components @vtmn/css): add report form in storybook 

---

.github/workflows/build-pr.yml
packages/showcases/react/package.json
packages/showcases/vue/package.json

Add missing dev dependencies
- No
❤️ Thank you!

docs: add missing devDependencies

---

.husky/pre-commit
package.json

Fix bug with pre-commit hook.
- No
❤️ Thank you!

fix: pre-commit errors

---

packages/sources/css/src/components/button/src/index.css

- There was only one letter-spacing for all the button size variant, there are now 3 variant for each size.
- Yes
❤️ Thank you!

fix(@vtmn/css): specify letter spacing for each size  of the button

---

packages/sources/css/presets/tailwind/tailwind-preset.js
packages/sources/css/src/components/alert/src/index.css
packages/sources/css/src/components/badge/src/index.css
packages/sources/css/src/components/chip/src/index.css
packages/sources/css/src/components/modal/src/index.css
packages/sources/css/src/components/popover/src/index.css
packages/sources/css/src/components/progressbar/src/index.css
packages/sources/css/src/components/rating/src/index.css
packages/sources/css/src/components/text-input/src/index.css
packages/sources/css/src/components/tooltip/src/index.css
packages/sources/css/src/design-tokens/src/typography.css

Close #749 
- Yes, I will send an email to people that uses `vtmn-font-normal` class (only 3 projects).
❤️ Thank you!

fix(@vtmn/css-tailwind-preset): font-normal class has two definitions

---

packages/sources/css/src/components/button/src/index.css

- revert the change on the min-height, it breaks the button itself
- No
❤️ Thank you!

refactor(@vtmn/css): button, revert the change on the min-height

---

packages/sources/react/src/index.ts

feat(@vtmn/react): add export for alert component

---

.github/workflows/build-main.yml
.github/workflows/build-pr.yml
README.md
packages/showcases/css/stories/components/divider/divider.stories.js
packages/showcases/css/stories/components/divider/examples/horizontal.html
packages/showcases/css/stories/components/divider/examples/overview.html
packages/showcases/css/stories/components/divider/examples/vertical.html
packages/sources/css/src/components/divider/README.md
packages/sources/css/src/components/divider/build.js
packages/sources/css/src/components/divider/package.json
packages/sources/css/src/components/divider/postcss.config.js
packages/sources/css/src/components/divider/sonar-project.properties
packages/sources/css/src/components/divider/src/index.css
packages/sources/css/src/components/index.css
workspace.json

- New divider component
- Two orientations : horizontale and verticale
- Five text variants : empty, default, center, start and end text.
- No
❤️ Thank you!

feat(@vtmn/css): add divider component

---

packages/showcases/css/stories/components/search/examples/on-content.html
packages/showcases/css/stories/components/search/examples/overview.html
packages/showcases/css/stories/components/search/examples/persistent.html
packages/showcases/css/stories/components/search/search.stories.js

I propose to use addon backgrounds instead of custom style for search component stories.
- No
❤️ Thank you!

docs(@vtmn/css-showcase): use addon backgrounds instead of custom style for search component stories

---

packages/sources/css/src/components/breadcrumb/src/index.css
packages/sources/css/src/components/tabs/src/index.css

add token focus-visible for breadcrumb and tabs
- No
❤️ Thank you!

feat(@vtmn/css): add token focus-visible for breadcrumb and tabs

---

packages/showcases/core/csf/components/VtmnCheckbox.csf.js
packages/showcases/core/csf/components/VtmnRadioButton.csf.js
packages/showcases/core/csf/components/VtmnToggle.csf.js
packages/showcases/react/stories/components/VtmnCheckbox/VtmnCheckbox.stories.tsx
packages/showcases/react/stories/components/VtmnRadioButton/VtmnRadioButton.stories.tsx
packages/showcases/react/stories/components/VtmnTextInput/VtmnTextInput.stories.tsx
packages/showcases/react/stories/components/VtmnToggle/VtmnToggle.stories.tsx
packages/sources/react/src/components/VtmnCheckbox/VtmnCheckbox.tsx
packages/sources/react/src/components/VtmnRadioButton/VtmnRadioButton.tsx
packages/sources/react/src/components/VtmnToggle/VtmnToggle.tsx
packages/sources/react/src/index.ts

Thanks, @gabbloquet for this request. For the history, see #831.
- No
❤️ Thank you!

fix(@vtmn/react): uncontrolled components

---

packages/sources/css/src/components/badge/src/index.css
packages/sources/css/src/components/breadcrumb/src/index.css
packages/sources/css/src/components/button/src/index.css
packages/sources/css/src/components/card/src/index.css
packages/sources/css/src/components/checkbox/src/index.css
packages/sources/css/src/components/chip/src/index.css
packages/sources/css/src/components/link/src/index.css
packages/sources/css/src/components/popover/src/index.css
packages/sources/css/src/components/progressbar/src/index.css
packages/sources/css/src/components/radio-button/src/index.css
packages/sources/css/src/components/rating/src/index.css
packages/sources/css/src/components/search/src/index.css
packages/sources/css/src/components/select/src/index.css
packages/sources/css/src/components/snackbar/src/index.css
packages/sources/css/src/components/tabs/src/index.css
packages/sources/css/src/components/toast/src/index.css
packages/sources/css/src/components/toggle/src/index.css
packages/sources/css/src/components/tooltip/src/index.css
workspace.json

- When consumed individually, some components were missing some properties (coming from tailwind preset) to behave correctly.
- Some imports were also missing, they have been added.
- The navbar was not puclished on npkg due to missing lines in a configuration file.
- No
❤️ Thank you!

fix(@vtmn/css): add missing imports + props

---

.github/workflows/build-main.yml
.github/workflows/build-pr.yml
README.md
packages/showcases/css/stories/components/tag/examples/overview.html
packages/showcases/css/stories/components/tag/tag.stories.js
packages/sources/css/src/components/chip/src/index.css
packages/sources/css/src/components/index.css
packages/sources/css/src/components/tag/README.md
packages/sources/css/src/components/tag/build.js
packages/sources/css/src/components/tag/package.json
packages/sources/css/src/components/tag/postcss.config.js
packages/sources/css/src/components/tag/sonar-project.properties
packages/sources/css/src/components/tag/src/index.css
packages/sources/css/src/design-tokens/src/themes/core-dark.css
packages/sources/css/src/design-tokens/src/themes/core-light.css
packages/sources/css/src/design-tokens/src/themes/default.css
workspace.json

- Add tag component
- Three variant colors
- Eight decorative colors
- No
❤️ Thank you!

feat(@vtmn/css): add tag component

---

packages/showcases/css/stories/components/quantity/examples/overview.html
packages/showcases/css/stories/components/select/examples/error.html
packages/showcases/css/stories/components/text-input/examples/disabled.html
packages/showcases/css/stories/components/text-input/examples/error.html
packages/showcases/css/stories/components/text-input/examples/multiline.html
packages/showcases/css/stories/components/text-input/examples/overview.html
packages/showcases/css/stories/components/text-input/examples/valid.html

- Thanks to this enhancement, screen reader will associate (and read) the helper message with the input.
- No breaking changes BUT you may include this new prop to your current input components if you are already using them.
❤️ Thank you!

feat(@vtmn/css): add aria-describedby prop for input components

---

packages/sources/css/presets/tailwind/tailwind-preset.js

Close #851 
- No
❤️ Thank you!

refactor(@vtmn/css-tailwind-preset): add transparent color

---

packages/showcases/css/stories/guidelines/iconography/iconography.stories.mdx

Close #714 
- No
❤️ Thank you!

docs(@vtmn/css-showcase): add iconography documentation

---

packages/showcases/css/stories/components/structure/skeleton/examples/overview.html
packages/showcases/icons/.storybook/preview-head.html
packages/sources/css/src/components/actions/button/src/index.css
packages/sources/css/src/components/forms/select/src/index.css
packages/sources/css/src/components/forms/text-input/src/index.css
packages/sources/css/src/components/indicators/badge/src/index.css
packages/sources/css/src/components/indicators/price/src/index.css
packages/sources/css/src/components/indicators/progressbar/src/index.css
packages/sources/css/src/components/indicators/tag/src/index.css
packages/sources/css/src/components/navigation/search/src/index.css
packages/sources/css/src/components/overlays/alert/src/index.css
packages/sources/css/src/components/overlays/modal/src/index.css
packages/sources/css/src/components/overlays/popover/src/index.css
packages/sources/css/src/components/overlays/snackbar/src/index.css
packages/sources/css/src/components/overlays/toast/src/index.css
packages/sources/css/src/components/overlays/tooltip/src/index.css
packages/sources/css/src/components/selection-controls/chip/src/index.css
packages/sources/css/src/components/selection-controls/quantity/src/index.css
packages/sources/css/src/components/selection-controls/toggle/src/index.css
packages/sources/css/src/components/structure/card/src/index.css
packages/sources/css/src/components/structure/skeleton/src/index.css
packages/sources/css/src/design-tokens/src/index.css
packages/sources/css/src/design-tokens/src/radius.css

Replace fixed `border-radius` values by design tokens
JIRA : https://decathlon.atlassian.net/jira/software/projects/DSRUN/boards/2922?selectedIssue=DSRUN-63
- No

feat(@vtmn/css): add radius design tokens + imports in css

---

.github/PULL_REQUEST_TEMPLATE.md

Include a step to add a design review with a core designer if the changes includes design improvements.
- No

feat(@vtmn/css): improve PR template

---

packages/sources/css/src/design-tokens/src/themes/core-dark.css
packages/sources/css/src/design-tokens/src/themes/core-light.css
packages/sources/css/src/design-tokens/src/themes/default.css

- add activeTertiaryReversedTransparent in dark theme
JIRA : https://decathlon.atlassian.net/jira/software/projects/DSRUN/boards/2922?selectedIssue=DSRUN-108
- No

feat(@vtmn/css): add activeTertiaryReversedTransparent

---

.prettierignore
.stylelintrc.json
packages/sources/css/src/design-tokens/src/base-colors.css

Add missing commas in some design tokens.
Reported by @Margot-ElMadi 
- No

fix(@vtmn/css-design-tokens): missing commas

---

packages/showcases/css/stories/components/overlays/snackbar/examples/overview.html

- Rename snackbar button variant from `secondary` to `ghost` 
JIRA : https://decathlon.atlassian.net/jira/software/projects/DSRUN/boards/2922?selectedIssue=DSRUN-107
- No breaking change, but you need to change manually your snackbar button variant.

feat(@vtmn/css): change snackbar button variant

---

packages/sources/css/src/components/structure/accordion/src/index.css

- Add a css rule to remove display of marker for the summary tag.
- Safari browser displayed a list-style-type even though it was removed by a property
- No

feat(@vtmn/css): remove acccordion list-type 

---

packages/sources/css/src/components/navigation/search/src/index.css

- Rename class name in CSS (it was badly recopied)
- The default search had a shadow, it shouldn't have.
- No

fix(@vtmn/css): fix incorrect class for css props

---

packages/sources/css/src/components/overlays/alert/src/index.css
packages/sources/css/src/components/overlays/popover/src/index.css
packages/sources/css/src/components/overlays/snackbar/src/index.css
packages/sources/css/src/components/overlays/toast/src/index.css
packages/sources/css/src/components/overlays/tooltip/src/index.css

- Add `oultine: 0;` to prevent outline to appear when focus
- No

feat(@vtmn/css): remove outline for overlays

---

packages/sources/css/src/components/actions/button/src/index.css

- Rename `button` hover color
- No

feat(@vtmn/css): rename hover brand to hover tertiary

---

packages/showcases/core/csf/guidelines/iconography.csf.js
packages/showcases/vue/stories/VtmnIcon/VtmnIcon.stories.js
packages/sources/vue/src/components/VtmnIcon/VtmnIcon.vue
packages/sources/vue/src/components/VtmnIcon/index.ts
packages/sources/vue/src/components/VtmnIcon/types.ts
packages/sources/vue/src/index.ts

Add Vue implementation of VtmnIcon component.
https://github.com/Decathlon/vitamin-web/issues/717
- No

feat(@vtmn/vue): add `VtmnIcon` component

---

packages/showcases/react/.storybook/preview.js
packages/showcases/svelte/.storybook/main.js
packages/showcases/svelte/stories/components/actions/VtmnButton/VtmnButton.stories.svelte
packages/showcases/svelte/stories/components/actions/VtmnLink/VtmnLink.stories.svelte
packages/showcases/svelte/stories/components/forms/VtmnTextInput/VtmnTextInput.stories.svelte
packages/showcases/svelte/stories/components/overlays/VtmnPopover/VtmnPopover.stories.svelte
packages/sources/svelte/rollup.config.js
packages/sources/svelte/src/components/actions/VtmnButton/VtmnButton.svelte
packages/sources/svelte/src/components/actions/VtmnLink/VtmnLink.svelte
packages/sources/svelte/src/components/forms/VtmnTextInput/VtmnTextInput.svelte
packages/sources/svelte/src/components/index.js
packages/sources/svelte/src/components/overlays/VtmnPopover/VtmnPopover.svelte

refactor(@vtmn/svelte): file structure

---

packages/sources/vue/src/components/actions/VtmnLink/VtmnLink.vue
packages/sources/vue/src/components/actions/VtmnLink/types.ts

feat(@vtmn/vue): add `VtmnLink` types

---

packages/showcases/css/stories/components/indicators/rating/examples/interactive.html
packages/showcases/css/stories/components/indicators/rating/examples/overview.html
packages/showcases/css/stories/components/indicators/rating/examples/read-only.html
packages/sources/css/src/components/indicators/rating/src/index.css

- Remove some bad examples of the usage of the rating
- Add new relevant examples
- Remove note and mark for interactive rating
- Add fit-content width to the component
- The showcase may present bad examples of the use of the rating components according to the documentation.
- No

docs(@vtmn/css): refactoring showcase doc for rating

---

packages/sources/css/src/components/forms/select/src/index.css

- move arrow position `4px` down
- Label element has been modified with line height, it changes the position of the arrow.
- Yes
- No

fix(@vtmn/css): fix arrow position select

---

packages/sources/vue/src/components/forms/VtmnSelect/VtmnSelect.vue
packages/sources/vue/src/components/forms/VtmnSelect/index.ts
packages/sources/vue/src/components/forms/VtmnSelect/types.ts
packages/sources/vue/src/components/forms/VtmnTextInput/VtmnTextInput.vue
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/index.ts

Make `VtmnTextInput` ready to use in a Vue project and add `VtmnSelect` component.
- No

feat(@vtmn/vue): add `VtmnTextInput` reactivity and `VtmnSelect` component

---

packages/showcases/vue/stories/components/indicators/VtmnLoader.stories.js
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/components/indicators/VtmnLoader/VtmnLoader.vue
packages/sources/vue/src/components/indicators/VtmnLoader/index.ts
packages/sources/vue/src/components/indicators/VtmnLoader/types.ts
packages/sources/vue/src/index.ts

Add `VtmnLoader` vue component
- No

feat(@vtmn/vue): add `VtmnLoader` component

---

packages/showcases/core/csf/components/indicators/price.csf.js
packages/showcases/css/stories/components/indicators/price/examples/overview.html
packages/showcases/react/stories/components/indicators/VtmnPrice/VtmnPrice.stories.tsx
packages/sources/react/package.json
packages/sources/react/src/components/indicators/VtmnPrice/VtmnPrice.tsx
packages/sources/react/src/components/indicators/VtmnPrice/index.ts
packages/sources/react/src/components/indicators/VtmnPrice/types.ts
packages/sources/react/src/index.ts

Add price component in React.
- No

feat(@vtmn/react): add `VtmnPrice` component

---

packages/showcases/core/csf/components/indicators/price.csf.js
packages/showcases/svelte/stories/components/indicators/VtmnPrice/VtmnPrice.stories.svelte
packages/showcases/vue/stories/components/indicators/VtmnPrice.stories.js
packages/sources/vue/package.json
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/components/indicators/VtmnPrice/VtmnPrice.vue
packages/sources/vue/src/components/indicators/VtmnPrice/index.ts
packages/sources/vue/src/components/indicators/VtmnPrice/types.ts
packages/sources/vue/src/index.ts

Add price component in Vue.
- No

feat(@vtmn/vue): add `VtmnPrice` component

---

packages/showcases/css/stories/components/structure/list/examples/overview.html
packages/sources/css/src/components/structure/list/src/index.css

- Refactoring of the paddings of the list
- The bottom border of the list where there is only text is full width
- List component has been improves
- No

refactor(@vtmn/css): fix border bottom + new paddings

---

packages/showcases/core/csf/components/actions/link.csf.js
packages/showcases/svelte/stories/components/actions/VtmnLink/VtmnLink.stories.svelte
packages/showcases/svelte/stories/components/forms/VtmnTextInput/VtmnTextInput.stories.svelte
packages/showcases/svelte/stories/components/indicators/VtmnBadge/VtmnBadge.stories.svelte
packages/showcases/svelte/stories/components/indicators/VtmnTag/VtmnTag.stories.svelte
packages/sources/svelte/src/components/actions/VtmnButton/VtmnButton.svelte

Fix some stories to match documentation and fix controls on storybook

docs(@vtmn/svelte): fix some doc + component

---

packages/sources/vue/src/components/forms/VtmnSelect/VtmnSelect.vue

Fix className typo (React syntax)
ClassName is React syntax, not Vue !
- No

fix(@vtmn/vue): className => class

---

packages/showcases/core/csf/components/structure/card.csf.js
packages/showcases/svelte/stories/components/structure/VtmnCard/VtmnCard.stories.svelte
packages/sources/svelte/package.json
packages/sources/svelte/rollup.config.js
packages/sources/svelte/src/components/index.js
packages/sources/svelte/src/components/structure/VtmnCard/VtmnCard.svelte
packages/sources/svelte/src/components/structure/VtmnCard/enums.js
packages/sources/svelte/src/components/structure/VtmnCard/test/VtmnCard.spec.js
packages/sources/svelte/src/components/structure/VtmnCard/test/VtmnCardWithSlot.svelte

Add a VtmnCard component
- Add 19 component tests

feat(@vtmn/svelte): add `VtmnCard` component

---

packages/showcases/core/csf/components/indicators/rating.csf.js
packages/showcases/svelte/stories/components/indicators/VtmnRating/VtmnRating.stories.svelte
packages/sources/svelte/package.json
packages/sources/svelte/rollup.config.js
packages/sources/svelte/src/components/index.js
packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte
packages/sources/svelte/src/components/indicators/VtmnRating/enum.js
packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRating.spec.js
packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRatingWithSlots.svelte
packages/sources/svelte/src/utils/math.js

Add VtmnRating component for svelte : 
- Need tests on the component

feat(@vtmn/svelte): add `VtmnRating` component

---

packages/showcases/core/csf/components/indicators/rating.csf.js
packages/showcases/svelte/stories/components/indicators/VtmnRating/VtmnRating.stories.svelte

Some missing files has not been push on the last PR (#1045)

fix(@vtmn/svelte): fix missing changes

---

packages/sources/svelte/package.json
packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
yarn.lock

- Fix missing package `@vtmn/css-checkout`
- Fix import css into modal

fix(@vtmn/svelte): missing import + fix style

---

packages/showcases/css/stories/components/structure/skeleton/examples/overview.html
packages/sources/css/src/components/structure/skeleton/src/index.css

refactor(@vtmn/css): avatar size of skeleton component

---

packages/showcases/css/stories/components/structure/card/examples/top-image.html
packages/sources/css/src/components/structure/card/src/index.css

- Add card showcase with a tag inside
- `Card` component can handle a tag inside the `top-image` variant
- No

feat(@vtmn/css-card): add tag showcase + css class

---

packages/showcases/svelte/stories/components/indicators/VtmnLoader/VtmnLoader.stories.svelte
packages/sources/svelte/package.json
packages/sources/svelte/rollup.config.js
packages/sources/svelte/src/components/index.js
packages/sources/svelte/src/components/indicators/VtmnLoader/VtmnLoader.svelte
packages/sources/svelte/src/components/indicators/VtmnLoader/enums.js
packages/sources/svelte/src/components/indicators/VtmnLoader/test/VtmnLoader.spec.js
packages/sources/svelte/src/components/indicators/VtmnTag/VtmnTag.svelte

Add loader component in Svelte.
- No

feat(@vtmn/svelte): add `VtmnLoader` component

---

packages/showcases/svelte/stories/components/indicators/VtmnRating/VtmnRating.stories.svelte

Fix proprety `readonly` on vtmn story rating

fix(@vtmn/svelte): fix readonly property on the story

---

packages/showcases/core/csf/components/selection-controls/quantity.csf.js
packages/showcases/svelte/stories/components/selection-controls/VtmnQuantity/VtmnQuantity.stories.svelte
packages/sources/svelte/package.json
packages/sources/svelte/rollup.config.js
packages/sources/svelte/src/components/index.js
packages/sources/svelte/src/components/selection-controls/VtmnQuantity/VtmnQuantity.svelte
packages/sources/svelte/src/components/selection-controls/VtmnQuantity/test/VtmnQuantity.spec.js

Add a new component `VtmnQuantity` for svelte

feat(@vtmn/svelte): add `VtmnQuantity` component

---

packages/showcases/core/csf/components/indicators/tag.csf.js
packages/showcases/react/stories/components/indicators/VtmnTag/VtmnTag.stories.tsx
packages/sources/react/package.json
packages/sources/react/src/components/indicators/VtmnBadge/VtmnBadge.tsx
packages/sources/react/src/components/indicators/VtmnTag/VtmnTag.tsx
packages/sources/react/src/components/indicators/VtmnTag/index.ts
packages/sources/react/src/components/indicators/VtmnTag/types.ts
packages/sources/react/src/index.ts
packages/sources/svelte/src/components/indicators/VtmnTag/VtmnTag.svelte
yarn.lock

feat(@vtmn/react): add `VtmnTag` component

---

packages/showcases/core/csf/components/overlays/alert.csf.js

- In the csf file of the VtmnToast. : type -> variant
- Yes
- No

feat(@vtmn/react): `VtmnToast` csf type -> variant

---

packages/showcases/svelte/stories/components/overlays/VtmnPopover/VtmnPopover.stories.svelte

- fix the display of the `VtmnPopover` story
- No

feat(@vtmn/svelte): fix popover display on storybook

---

packages/sources/css/src/components/indicators/price/src/index.css

- Set `line-height` to 1 to prevent alignment problems
- No

feat(@vtmn/css): `Price` fix line-height

---

packages/showcases/core/csf/components/structure/skeleton.csf.js
packages/showcases/vue/stories/components/structure/VtmnSkeleton/VtmnSkeleton.stories.js
packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
packages/sources/svelte/src/components/structure/VtmnSkeleton/test/vtmnSkeleton.spec.js
packages/sources/vue/package.json
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/components/structure/VtmnSkeleton/VtmnSkeleton.vue
packages/sources/vue/src/components/structure/VtmnSkeleton/index.ts
packages/sources/vue/src/components/structure/VtmnSkeleton/types.ts
packages/sources/vue/src/index.ts

feat(@vtmn/vue): add `VtmnSkeleton` component

---

packages/showcases/core/csf/components/structure/skeleton.csf.js
packages/showcases/react/stories/components/structure/VtmnSkeleton/VtmnSkeleton.stories.tsx
packages/sources/react/package.json
packages/sources/react/src/components/structure/VtmnSkeleton/VtmnSkeleton.tsx
packages/sources/react/src/components/structure/VtmnSkeleton/index.ts
packages/sources/react/src/components/structure/VtmnSkeleton/types.ts
packages/sources/react/src/index.ts
packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
packages/sources/svelte/src/components/structure/VtmnSkeleton/test/vtmnSkeleton.spec.js

feat(@vtmn/react): add `VtmnSkeleton` component

---

packages/sources/css/src/components/selection-controls/quantity/src/index.css

Close #1098 
Before:
After: 
- No
Source: https://stackoverflow.com/a/23374725

fix(@vtmn/css): quantity inner and outer spin buttons

---

packages/showcases/core/csf/components/structure/accordion.csf.js
packages/showcases/svelte/stories/components/structure/VtmnAccordion/VtmnAccordion.stories.svelte
packages/showcases/vue/stories/components/structure/VtmnAccordion/VtmnAccordion.stories.js
packages/sources/svelte/src/components/structure/VtmnAccordion/VtmnAccordion.svelte
packages/sources/vue/package.json
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/components/structure/VtmnAccordion/VtmnAccordion.vue
packages/sources/vue/src/components/structure/VtmnAccordion/index.ts
packages/sources/vue/src/index.ts

feat(@vtmn/vue): add `VtmnAccordion` component

---

packages/showcases/core/csf/components/overlays/popover.csf.js
packages/showcases/react/stories/components/overlays/VtmnPopover/VtmnPopover.stories.tsx
packages/showcases/svelte/stories/components/overlays/VtmnPopover/VtmnPopover.stories.svelte
packages/sources/react/package.json
packages/sources/react/src/components/overlays/VtmnPopover/VtmnPopover.tsx
packages/sources/react/src/components/overlays/VtmnPopover/index.ts
packages/sources/react/src/components/overlays/VtmnPopover/types.ts
packages/sources/react/src/index.ts
packages/sources/svelte/src/components/overlays/VtmnPopover/VtmnPopover.svelte

feat(@vtmn/react): add `VtmnPopover` component

---

packages/showcases/core/csf/components/selection-controls/quantity.csf.js
packages/showcases/react/stories/components/selection-controls/VtmnQuantity/VtmnQuantity.stories.tsx
packages/sources/react/src/components/selection-controls/VtmnQuantity/VtmnQuantity.tsx
packages/sources/react/src/components/selection-controls/VtmnQuantity/index.ts
packages/sources/react/src/index.ts

This P.R aims to add the quantity component
#824
- No

feat(@vtmn/react): add `VtmnQuantity` component

---

packages/showcases/react/stories/components/overlays/VtmnAlert/VtmnAlert.stories.tsx
packages/showcases/react/stories/components/overlays/VtmnToast/VtmnToast.stories.tsx
packages/showcases/vue/stories/components/overlays/VtmnAlert/VtmnAlert.stories.js
packages/showcases/vue/stories/components/overlays/VtmnTooltip/VtmnTooltip.stories.js
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/components/overlays/VtmnAlert/VtmnAlert.vue
packages/sources/vue/src/components/overlays/VtmnAlert/index.ts
packages/sources/vue/src/components/overlays/VtmnAlert/types.ts
packages/sources/vue/src/index.ts

- Add `VtmnAlert` component
- No

feat(@vtmn/vue): add `VtmnAlert` component

---

packages/showcases/css/stories/components/overlays/popover/examples/overview.html
packages/sources/css/src/components/overlays/popover/src/index.css

- Improvements have been made for the alignment
- The popover should ne displayed from a action component like a `button` or a `link` but the alignment of the popover with these compoents wasn't good.
- No

refactor(@vtmn/css): improve placement popover

---

packages/sources/vue/src/components/indicators/VtmnBadge/VtmnBadge.vue
packages/sources/vue/src/components/overlays/VtmnAlert/VtmnAlert.vue
packages/sources/vue/src/components/overlays/VtmnPopover/VtmnPopover.vue
packages/sources/vue/src/components/overlays/VtmnTooltip/VtmnTooltip.vue
packages/sources/vue/src/components/selection-controls/VtmnChip/VtmnChip.vue
packages/sources/vue/src/components/structure/VtmnAccordion/VtmnAccordion.vue
packages/sources/vue/src/components/structure/VtmnSkeleton/VtmnSkeleton.vue

refactor(@vtmn/vue): add missing prop types

---

packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
packages/sources/svelte/src/components/structure/VtmnSkeleton/test/vtmnSkeleton.spec.js

Add `$$restProps` on `VtmnSkeleton` + unit tests 
No breaking changes

fix(@vtmn/svelte): add `$$restProps` on `VtmnSkeleton`

---

packages/showcases/css/stories/components/actions/dropdown/examples/overview.html
packages/sources/css/src/components/actions/dropdown/src/index.css
yarn.lock

- Fix a bug where the `dropdown` menu scrolls to the top when a option is selected
- Add more accessibility to the component with a `role="group"` and a `aria-labelledby` 
- No

feat(@vtmn/css): improve `dropdown` a11y + fix bug scrolltop

---

packages/sources/css/src/components/structure/card/src/index.css

fix(@vtmn/css-card): missing import of spacings

---

packages/showcases/css/stories/components/actions/dropdown/examples/overview.html
packages/sources/css/src/components/actions/dropdown/src/index.css
yarn.lock

- A dropdown item takes 100% `width`
- The check state is now aligned from the end border of the dropdown item
- The `divider` of the last `dropdown` item is not displayed if by any chance it is set in the html
- In dropdown, if an item has a longer text, the check is not aligned with the others
- No

fix(@vtmn/css): `dropdown` adjustments

---

packages/showcases/css/stories/components/overlays/alert/examples/demo.runscript.js
packages/showcases/css/stories/components/overlays/modal/examples/demo.runscript.js
packages/showcases/css/stories/components/overlays/snackbar/examples/demo.runscript.js
packages/showcases/css/stories/components/overlays/toast/examples/demo.runscript.js

- Remove `html` template string 
- No

fix(@vtmn/css): debug demo showcases

---

packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte

Improvement of the import of the style by applying them in the head

refactor(@vtmn/svelte): `VtmnModal` import style in head

---

packages/showcases/css/stories/components/structure/accordion/examples/overview.html
packages/showcases/react/stories/components/structure/VtmnAccordion/VtmnAccordion.stories.tsx
packages/showcases/svelte/stories/components/structure/VtmnAccordion/VtmnAccordion.stories.svelte
packages/sources/react/src/components/structure/VtmnAccordion/VtmnAccordion.tsx
packages/sources/svelte/src/components/structure/VtmnAccordion/VtmnAccordion.svelte
packages/sources/vue/src/components/structure/VtmnAccordion/VtmnAccordion.vue

- Replace every `secondary` buttons inside `accordion` by a `primary`
- The `secondary` variant buttons are not accessible and need to be changed
- No breaking changes, but you need to nest an accessible button variant

feat(@vtmn/svelte, @vtmn/react, @vtmn/css): accordion, change `button` variant

---

packages/showcases/core/csf/components/indicators/rating.csf.js
packages/showcases/core/csf/components/navigation/search.csf.js
packages/showcases/core/csf/components/overlays/alert.csf.js
packages/showcases/core/csf/components/overlays/snackbar.csf.js
packages/showcases/core/csf/components/selection-controls/checkbox.csf.js
packages/showcases/core/csf/components/selection-controls/quantity.csf.js
packages/showcases/core/csf/components/selection-controls/radio-button.csf.js
packages/showcases/core/csf/components/selection-controls/toggle.csf.js
packages/showcases/core/csf/components/structure/card.csf.js

- Renaming some values.
- Rework some sentences.
- Add default values
- Alignement of the documentation
- No

docs(@vtmn/showcase-core): refacto docs csf

---

packages/showcases/react/stories/components/forms/VtmnSelect/VtmnSelect.stories.tsx
packages/showcases/vue/stories/components/forms/VtmnSelect/VtmnSelect.stories.js

docs(@vtmn/vue & @vtmn/react): add `VtmnSelect` component documentation for Vue & improve React documentation

---

packages/showcases/vue/stories/components/structure/VtmnList/VtmnList.stories.js
packages/sources/vue/package.json
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/components/structure/VtmnList/VtmnList.vue
packages/sources/vue/src/components/structure/VtmnList/index.ts
packages/sources/vue/src/components/structure/VtmnListItem/VtmnListItem.vue
packages/sources/vue/src/components/structure/VtmnListItem/index.ts
packages/sources/vue/src/components/structure/VtmnListItem/types.ts
packages/sources/vue/src/index.ts

feat(@vtmn/vue): add `VtmnList` component

---

packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModal.spec.js

Add `id` attribute to the `VtmnModal.svelte`

fix(@vtmn/svelte): add id to `VtmnModal`

---

packages/showcases/vue/stories/components/structure/VtmnCard/VtmnCard.stories.js
packages/sources/css/src/components/overlays/alert/src/index.css

fix(@vtmn/css): visual regression of alert component

---

packages/sources/react/src/components/forms/VtmnSelect/VtmnSelect.tsx
packages/sources/react/src/components/forms/VtmnTextInput/VtmnTextInput.tsx

feat(@vtmn/react): add props on text input and select to control their label

---

packages/sources/css/src/components/overlays/modal/src/index.css

fix(@vtmn/css): add modal padding

---

packages/sources/svelte/src/components/actions/VtmnLink/VtmnLink.svelte
packages/sources/svelte/src/components/actions/VtmnLink/test/VtmnLink.spec.js
packages/sources/svelte/src/components/actions/VtmnLink/test/VtmnLinkWithSlots.svelte

Add `on:click` event to be trigger when user click on the component `VtmnLink`

fix(@vtmn/svelte): add on:click event `VtmnLink`

---

packages/sources/css/presets/tailwind/package.json
packages/sources/css/presets/tailwind/src/index.ts
packages/sources/css/presets/tailwind/src/theme.ts
packages/sources/css/presets/tailwind/tsconfig.json
yarn.lock

emit ts declaration files to get full typesafety on @vtmn/css-tailwind-preset
https://github.com/Decathlon/vitamin-web/issues/1215#issuecomment-1195333961
- No
i'm not completely familiar with the repo and its multiple packages so I'd like if you could double check that I didnt break anything

fix(@vtmn/css-tailwind-preset): add types

---

packages/showcases/css/stories/components/forms/select/examples/disabled.html
packages/showcases/css/stories/components/forms/select/examples/error.html
packages/showcases/css/stories/components/forms/select/examples/overview.html
packages/showcases/svelte/stories/components/forms/VtmnSelect/VtmnSelect.stories.svelte
packages/sources/svelte/src/components/forms/VtmnSelect/VtmnSelect.svelte
packages/sources/svelte/src/components/forms/VtmnSelect/test/VtmnSelect.spec.js

Related comment on our Slack. Thanks a lot Jordi & Kevin:
`autocomplete` valid values are `"on"` & `"off"`.
- No

fix(@vtmn/svelte): `VtmnSelect` autocomplete

---

packages/sources/assets/package.json
packages/sources/assets/svgo.config.js

This PR is there to fix a problem that our SVG assets doesn't have any `viewBox`.
Thanks Margot for reporting this on Slack.
- No

fix(@vtmn/assets): viewboxes are absent/incorrect in SVG & sprite

---

packages/sources/css/package.json
packages/sources/css/src/preflight.css
packages/sources/svelte/package.json
packages/sources/svelte/src/components/navigation/VtmnTabs/VtmnTabs.svelte

fix(@vtmn/css, @vtmn/svelte): missing preflight for some component like `VtmnTabs`

---

packages/showcases/css/stories/components/actions/button/examples/conversion.html
packages/showcases/css/stories/components/actions/button/examples/ghost-reversed.html
packages/showcases/css/stories/components/actions/button/examples/ghost.html
packages/showcases/css/stories/components/actions/button/examples/overview.html
packages/showcases/css/stories/components/actions/button/examples/primary-reversed.html
packages/showcases/css/stories/components/actions/button/examples/primary.html
packages/showcases/css/stories/components/actions/button/examples/secondary.html
packages/showcases/css/stories/components/actions/button/examples/tertiary.html

Icon right are absent because the icon doesn't exist anymore.
- No

docs(@vtmn/css): fix button showcase for icon right

---

packages/showcases/css/.storybook/preview-body.html
packages/showcases/css/.storybook/preview-head.html
packages/showcases/icons/.storybook/preview-body.html
packages/showcases/icons/.storybook/preview-head.html
packages/showcases/react/.storybook/preview-body.html
packages/showcases/react/.storybook/preview-head.html
packages/showcases/svelte/.storybook/preview-body.html
packages/showcases/svelte/.storybook/preview-head.html
packages/showcases/svelte/.storybook/preview.js
packages/showcases/svelte/package.json
packages/showcases/vue/.storybook/preview-body.html
packages/showcases/vue/.storybook/preview-head.html
packages/sources/css/src/components/forms/select/src/index.css
packages/sources/css/src/components/structure/card/src/index.css

fix(@vtmn/showcase-svelte): showcase header & Card component in Storybook Svelte

---

packages/sources/svelte/rollup.config.js
packages/sources/svelte/src/components/navigation/VtmnTabsItem/VtmnTabsItem.svelte
packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
packages/sources/svelte/src/components/overlays/VtmnPopover/VtmnPopover.svelte
packages/sources/svelte/src/components/overlays/VtmnTooltip/VtmnTooltip.svelte
packages/sources/svelte/src/components/selection-controls/VtmnChip/VtmnChip.svelte
packages/sources/svelte/src/components/structure/VtmnListItem/VtmnListItem.svelte
packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
packages/sources/vue/src/components/navigation/VtmnTabsItem/VtmnTabsItem.vue

fix(@vtmn/svelte): lint warnings

---

packages/sources/svelte/rollup.config.js

Issue with the svelte rollup, the css generated output doesn't generate correctly the base-10.

build(@vtmn/svelte): fix css build

---

.github/stale.yml

I propose to add https://github.com/probot/stale
- No

config: add probot/stale in order to close issues & PRs that are inactive

---

packages/sources/css/src/components/structure/card/src/index.css

fix(@vtmn/css-card): align padding between variants

---

packages/showcases/core/csf/components/navigation/search.csf.js
packages/showcases/css/stories/components/navigation/search/examples/default.html
packages/showcases/css/stories/components/navigation/search/examples/on-content.html
packages/showcases/css/stories/components/navigation/search/examples/overview.html
packages/showcases/css/stories/components/navigation/search/examples/persistent.html
packages/sources/react/src/components/navigation/VtmnSearch/VtmnSearch.tsx
packages/sources/svelte/src/components/navigation/VtmnSearch/VtmnSearch.svelte
packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue

Closes #1358
For your information, I will ask designers to rename the Figma variant "Show search" => "Show search button"
- No

feat: add a prop to hide search button in `Search` component

---

packages/sources/css/src/components/selection-controls/quantity/src/index.css

This PR fixes a problem with `full-width` in `Quantity` component since it was broken when the new prop `size` arrives.
- No

fix(@vtmn/css-quantity): full-width

---

packages/showcases/core/csf/components/navigation/navbar-link.csf.js
packages/showcases/css/stories/components/navigation/navbar/examples/overview.html
packages/showcases/react/stories/components/navigation/VtmnNavbarLink/VtmnNavbarLink.stories.tsx
packages/showcases/svelte/stories/components/navigation/VtmnNavbar/VtmnNavbar.stories.svelte
packages/showcases/svelte/stories/components/navigation/VtmnNavbarLink/VtmnNavbarLink.stories.svelte
packages/showcases/vue/stories/components/navigation/VtmnNavbarLink/VtmnNavbarLink.stories.js
packages/sources/css/src/components/navigation/navbar/src/index.css
packages/sources/react/src/components/navigation/VtmnNavbarLink/VtmnNavbarLink.tsx
packages/sources/react/src/components/navigation/VtmnNavbarLink/index.ts
packages/sources/react/src/index.ts
packages/sources/svelte/src/components/index.js
packages/sources/svelte/src/components/indicators/VtmnProgressbar/VtmnProgressbarCircular.svelte
packages/sources/svelte/src/components/indicators/VtmnProgressbar/VtmnProgressbarLinear.svelte
packages/sources/svelte/src/components/navigation/VtmnNavbarLink/VtmnNavbarLink.svelte
packages/sources/svelte/src/components/navigation/VtmnNavbarLink/test/VtmnNavbarLink.spec.js
packages/sources/vue/src/components/index.ts
packages/sources/vue/src/components/navigation/VtmnNavbar/VtmnNavbar.vue
packages/sources/vue/src/components/navigation/VtmnNavbarLink/VtmnNavbarLink.vue
packages/sources/vue/src/components/navigation/VtmnNavbarLink/index.ts
packages/sources/vue/src/index.ts

feat: add navbar link on `VtmnNavbar` component

---

packages/sources/css/src/components/structure/list/src/index.css

Refer to #1383 
Issue with the build

feat(@vtmn/css): add position relative on `VtmnListItem`

---

.vscode/extensions.json

Update recommendation (`.vscode/extensions.json`) for mdx vscode extension from [silvenon.mdx](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx) to [unifiedjs.vscode-mdx](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx)
This extension is [deprecated](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx) and point to a new one : [unifiedjs.vscode-mdx](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx)
- No

chore: replace deprecated mdx vscode extension

---

packages/sources/css/presets/tailwind/README.md

Minor README.md change related to the package name in the install section.
- No

docs(readme): change wrong package name reference

---

.github/ISSUE_TEMPLATE/documentation_improvement.md

Change documentation_improvement.md with web Slack channel

chore: Update documentation_improvement.md

---

packages/sources/css/src/components/selection-controls/toggle/src/index.css

fix(@vtmn/css): the thumb of the Toggle component doesn't have the right color in dark mode

---

packages/sources/vue/src/components/overlays/VtmnAlert/VtmnAlert.vue

Fix issue with the build 
https://github.com/Decathlon/vitamin-web/actions/runs/6349658717/job/17248170407
- Yes
- No

fix(build): fix lint issues

---

packages/sources/svelte/src/components/actions/VtmnButton/VtmnButton.svelte
packages/sources/svelte/src/components/actions/VtmnLink/VtmnLink.svelte
packages/sources/svelte/src/components/forms/VtmnSelect/VtmnSelect.svelte
packages/sources/svelte/src/components/forms/VtmnTextInput/VtmnTextInput.svelte
packages/sources/svelte/src/components/overlays/VtmnPopover/VtmnPopover.svelte
packages/sources/svelte/src/components/selection-controls/VtmnCheckbox/VtmnCheckbox.svelte
packages/sources/svelte/src/components/selection-controls/VtmnToggle/VtmnToggle.svelte

Add some refs on the svelte components in order to interact with them (focus ...)
- No

feat(`@vtmn/svelte`): export ref on components

---

packages/sources/svelte/src/components/selection-controls/VtmnToggle/VtmnToggle.svelte

Add missing event `on:change` / `on:check` on `VtmnToggle`
- Yes
- No

feat(`@vtmn/svelte`): add missing events on `VtmnToggle`
