- .github/workflows/build-main.yml
- package.json
- packages/showcases/css/package.json
- yarn.lock
Storybook deployment is managed thanks to [storybook-deloyer](https://github.com/storybookjs/storybook-deployer)
which pushes all storybooks of this monorepo to github pages.
It is automatically done on merge on main branch.
It should be automatically deployed after merging this PR to https://decathlon.github.io/vitamin-web.
Aggregation page of the multiple storybooks [can be personnalized](https://github.com/storybookjs/storybook-deployer#customize-monorepo-indexhtml) (not addressed in this PR).
For now it's a basic page listing storybooks using the name/description in each `package.json` :
See https://thollander.github.io/vitamin-web for example.
> ci: deploy storybook

- packages/showcases/css/.storybook/preview-head.html
- packages/sources/css/src/design-tokens/src/typography.css
This Pull Request fixes #30 & #29. I have also replaced `px` units on typography's design tokens with a relative unit: `rem` (see #19).
I've used official values now validated by designers available here: https://www.decathlon.design/726f8c765/p/860e14-typography
Thanks in advance for your review! :)
- No
> refactor(css design tokens): typography line heights + font size from px to rem unit

- packages/sources/react/package.json
- packages/sources/react/src/components/VtmnButton/VtmnButton.tsx
As I've struggled myself with `React` types in `TypeScript` recently and as I've stumbled upon your repo (looking for inspiration for my own `rollup` configuration 😄), I decided to suggest a few changes based on my own experience
I've used this guideline as a reference: https://react-typescript-cheatsheet.netlify.app/
The sections I've used are these ones:
- https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components
- https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase#wrappingmirroring-a-html-element
Following these guidelines may save you a few headaches in the long run 😄  (trust me, I've been there)
Also, I realized the …
> refactor(@vtmn/react): use more conventional types

- packages/sources/css/src/components/button/src/index.css
Add line-heights to cta in order to give them a fitting default height.
According to [design-system statements](https://www.decathlon.design/726f8c765/p/8008f8-button/t/58ed03) :
**S should be 32px** 
that's 2rem 
that's **_0.875rem_** (font-size) * **_~1.2857_** (line-height) + **_0.4375rem_** (padding-top) + **_0.4375rem_** (padding-bottom)
**M should be 48px** 
that's 3rem 
that's **_1rem_** (font-size) * **_1.25_** (line-height) + **_0.875rem_** (padding-top) + **_0.875rem_** (padding-bottom)
**L should be 64px** 
that's 4rem 
that's **_1.25rem_** (font-size) * **_1.2_** (line-height) + **_1.25rem_** (padding-top) + **_1.25rem_** (padding-bottom)
> refactor(@vtmn/css): add line-heights to buttons

- packages/sources/css/config/tailwind/tailwind.config.js
This PR aims to provide a shorten version of vtmn screens prefixes as long as a new screen scope for mobile only styles.
Yes
As this PR change the existing screen names we would need to rename them everywhere they are being used.
- tablet = tb
- small desktop = sd
- medium-desktop = md
- large-desktop = ld
❤️ Thank you!
> refactor(@vtmn/css): add mobile screen in tailwind configuration

- packages/sources/css/src/components/text-input/src/index.css
Add more specification on vtmn-text-input, such as what is already done on textarea.
**e.g: .vtmn-text-input => input.vtmn-text-input**
- No
This enhancement has for objective to improve inputs targeting, which is necessary to override our Cube legacy input css in NFS new account forms, using Vitamin style.
❤️ Thank you!
> feat(vtmn-text-input): Add more specification on inputs

- packages/sources/css/README.md
Edit the html import, replace the two html links by one that does the same thing.
Add another way of importing by using the css import rule (see [doc](https://developer.mozilla.org/fr/docs/Web/CSS/@import)).
- No
> docs(@vtmn/css): edit fonts import documentation

- packages/showcases/core/src/components/VtmnLink.csf.js
- packages/showcases/react/stories/components/VtmnLink/VtmnLink.stories.tsx
- packages/showcases/svelte/stories/components/VtmnLink/VtmnLink.stories.js
- packages/showcases/svelte/stories/components/VtmnLink/VtmnLinkView.svelte
- packages/sources/svelte/rollup.config.js
- packages/sources/svelte/src/components/VtmnLink.svelte
- init a new format of file `showcases/core/src/components/{component}.csf.js` ([Component Story Format](https://storybook.js.org/docs/react/writing-stories/introduction?_sm_au_=iVV3QqfrFv0vR8JHVWsfvK70kM0Mc#component-story-format)) => first step to have a uniform implementation across frameworks
- add link component version for Svelte
> feat(@vtmn/svelte): add link component

- packages/sources/css/src/components/checkbox/src/index.css
- packages/sources/css/src/components/radio-button/src/index.css
- When a radio or checkbox is focus-visible, the hover effect doesn't apply and make the focus-visible state priority.
- No
❤️ Thank you!
> fix(@vtmn/css): no more hover effect over focus-visible state (checkbox/radio)

- packages/sources/icons/src/templates/css.hbs
- Vitamix icons sprites are now flex and vertically aligned by default (previously: inline-flex). Enabling the centering of the sprites in div and preventing the height of the icon to be higher than the sprite.
- Yes
- If you translate manually your icons with an absolute position or by using transform property, you may need to remove these code lines and use display-flex properties to center or align your icon.
❤️ Thank you!
> feat(@vtmn/icons): change default display of vtmx sprites

- .gitattributes
- .husky/pre-commit
- package.json
- packages/showcases/svelte/.storybook/main.js
- packages/showcases/svelte/package.json
- packages/showcases/svelte/stories/components/VtmnPopover/VtmnPopover.stories.svelte
- packages/sources/svelte/src/components/VtmnButton.svelte
- packages/sources/svelte/src/components/VtmnLink.svelte
- packages/sources/svelte/src/components/VtmnPopover.svelte
- packages/sources/svelte/src/components/VtmnTextInput.svelte
- packages/sources/svelte/src/utils/classnames.js
- yarn.lock
I added : 
- a Svelte component over the `popover` vitamin design :) 
- its stories
- a `classnames` utils, a first step to concatenate classNames and removing falsy ones.
I updated current components in order to use this util. 
Please note that it could be useful in other frameworks, such as React.
I took the liberty to add support for Svelte files in prettier, and for the Svelte CSF story format.
- No (I don't think so)
> feat(@vtmn/svelte): add popover component

- README.md
- package.json
The goal of this PR is to delete the `"prepare"` NPM script because we don't need it. Thanks a lot @thollander for the idea.
References:
- https://github.com/Decathlon/vitamin-web/pull/516#issuecomment-907016234
- https://github.com/Decathlon/vitamin-web/pull/516#issuecomment-917117505
- https://github.com/Decathlon/vitamin-web/pull/516#issuecomment-917117505
- No
> chore: delete prepare npm script

- packages/showcases/css/.storybook/preview-head.html
- packages/showcases/react/.storybook/preview-head.html
- packages/showcases/web-components/.storybook/preview-head.html
- packages/sources/css/src/components/alert/src/index.css
- packages/sources/css/src/components/modal/src/index.css
- packages/sources/css/src/components/popover/src/index.css
- packages/sources/css/src/components/snackbar/src/index.css
- packages/sources/css/src/components/toast/src/index.css
- packages/sources/css/src/components/tooltip/src/index.css
- packages/sources/css/src/design-tokens/src/index.css
- packages/sources/css/src/design-tokens/src/z-indexes.css
Close #634 by putting our extented toolbars for CSS, Web Components and React showcases to 100.
I've also take the opportunity to align our z-index by respecting the decision matrix from our documentation (from 1001 to 1006):
[Details here](https://www.decathlon.design/726f8c765/p/88386e-overlays).
- No
❤️ Thank you!
> docs: fix extended toolbar z-index and align z-index overlays

- packages/sources/svelte/src/components/VtmnButton.svelte
I tried to use the Svelte `<VtmnButton>` in my project as following :
```
<VtmnButton on:click={handler}>My button</VtmnButton>
```
But it doesn't work as expected. When I click on the button, the handler function is never called. 🤔 
➡️  By looking at the source code of the component I found that the `on:click` attribute was not set on the `button` tag. If not set, the component cannot emit the click event.
This PR fixes this issue.
- No
❤️ Thank you!
> fix(@vtmn/svelte): add on:click on VtmnButton to handle click events

- packages/sources/react/src/components/VtmnTextInput/VtmnTextInput.tsx
- packages/sources/react/src/components/VtmnToggle/VtmnToggle.tsx
Fix compilation error for React components ; 
* React.memo doesn't support components returning an array,
  hence rollbacking to fragment syntax.
* `input`s and `textarea`s don't have the same valid HTML attributes.
   As the component uses `multiline` to know when to render one or the other,
   I explicited in the type that if `multiline` is true,
   then the expected attributes are of textarea,
   and that if `multiline` is false, the expected attributes are of input.
* VtmnToggle overrides `size` with its own semantic, 
it implies that VtmnToggleProps doesn't fully extends HTMLInputProps
Closes #650 
- Yes
User of VtmnTextInput  using `multiline=true` and explicitly writing a callback …
> fix(@vtmn/react): TS compilation error 

- packages/sources/svelte/src/components/VtmnTextInput.svelte
I tried two-way binding on `<VtmnTextInput />`, with a simple example like this :
```
<VtmnTextInput bind:value={name} />
<h1>Hello {name}!</h1>
```
... but this code doesn't work as expected. When typing a new text in the input, the displayed text in the `h1` is not modified.
This PR fixes this issue by making the `<VtmnTextInput>`'s two-way binding work in one-line (`input type="text"`) and multi-lines mode (`textarea`).
- No
❤️ Thank you!
> fix(@vtmn/svelte): allow to use two-way binding on VtmnTextInput

- packages/showcases/react/stories/components/VtmnTooltip/VtmnTooltip.stories.tsx
- packages/sources/react/src/components/VtmnTooltip/VtmnTooltip.tsx
- packages/sources/react/src/components/VtmnTooltip/types.ts
Refacto of the position tooltip props, from an enum to a type to comply with current vtmn react component behaviour, as it will be easier to modify components props from sending the position directly as a string value from an authorized range declare in the position exported Type 
As seen in my issue https://github.com/Decathlon/vitamin-web/issues/719 i don't think this is a breaking change but maybe I'm wrong ?
- No
The position of tooltip is now modifiable easily by users because before as it was an enum, developers must create the enum in their local architecture, now it complies with the behaviour if current vtmn react components, the props which must receive certain string values are …
> refactor(@vtmn/react): VtmnTooltipPosition props from enum to type

- packages/sources/svelte/src/components/VtmnButton.svelte
In Svelte, optionnal props must have a nullish default value, otherwise the compiler displays warnings like the following :
`<VtmnButton> was created without expected prop 'iconAlone'`.
This PR add a default value (`undefined`) to optionnal props in `<VtmnButton>`.
- No
❤️ Thank you!
> fix(@vtmn/svelte): fix optional props values

- packages/showcases/core/csf/components/VtmnIcon.csf.js
- packages/sources/react/src/components/VtmnIcon/VtmnIcon.tsx
- packages/sources/react/src/components/VtmnIcon/types.ts
This is an update to react [icon component](https://github.com/Decathlon/vitamin-web/issues/717) variants
- **It allows icons to have an inherited color.**
_Why_ : This makes sense as icons doesn't have color restrictions, and when associated with text, an icon should be able to hold the same color.
_How_ : This PR propose a `neutral` variant keyword, when stated outputted inline color value is `inherit`
- **It changes the variant keyword `danger` as `negative`**
and output color value as `var(--vtmn-semantic-color_content-negative)`,
rather than `var(--vtmn-semantic-color_content-danger)` (that doesn't exist - stating a `danger` variant right now output a black color)
- Yes
`danger` …
> feat(@vtmn/react): update icon variants

- packages/sources/css/src/components/alert/src/index.css
- packages/sources/css/src/design-tokens/src/animations.css
When the alert animation is triggered, the alert can be visible before and after the start/end of it.
Close #761 
- No
> fix(@vtmn/css): animation alert disapearing

- packages/showcases/css/stories/components/badge/examples/overview.html
- packages/sources/css/src/components/badge/src/index.css
- packages/sources/css/src/components/chip/src/index.css
- Fix alignements  + font style shortcut
- Badge component had font styes shortcut and it seems it bugs so I separated them like before to avoid design flaws.
- Chip component had some minor misalignments, I corrected them.
- No
> feat(@vtmn/css): fix alignements  + font style shortcut

- packages/sources/react/src/components/VtmnTooltip/VtmnTooltip.tsx
fix TS typings on children (this might be needed in multiple places and not just that one change)
currently, passing multiple elements such as:
```tsx
<VtmnTooltip tooltip={row.original.error_message} position="right" className="flex aic">
<VtmnIcon value="information-line" color="brand-digital" size={16} />
<Box ml="1">{value}</Box>
</VtmnTooltip>
```
triggers this typescript error (while this is valid JSX)
`This JSX tag's 'children' prop expects a single child of type 'Element', but multiple children were provided.ts(2746)`
current workaround is adding a pointless fragment:
```tsx
<VtmnTooltip tooltip={row.original.error_message} position="right" className="flex aic">
<>
<VtmnIcon value="information-line" color="brand-digital" size={16} />
<Box ml="1">{value}</Box>
</>
</VtmnTooltip> …
```
> fix(@vtmn/react): children typing in `VtmnTooltip`

- packages/sources/css/src/design-tokens/src/themes/core-dark.css
- packages/sources/css/src/design-tokens/src/themes/core-light.css
- packages/sources/css/src/design-tokens/src/themes/default.css
- rename `hoverBrandReversedTransparent` into `hoverTertiaryReversedTransparent`
- JIRA : https://decathlon.atlassian.net/jira/software/projects/DSRUN/boards/2922?selectedIssue=DSRUN-161
- No
> feat(@vtmn/css): rename hoverBrandReversedTransparent

- packages/showcases/css/stories/components/indicators/rating/examples/interactive.html
- packages/showcases/css/stories/components/indicators/rating/examples/overview.html
- packages/showcases/css/stories/components/indicators/rating/examples/read-only.html
- Add `disabled` to rating checkboxes to prevent interactivty
- Remove `aria-disabled` from all non-interactive rating components
- No, but make sure to add `disabled` value to your `checkbox` inside the rating
> feat(@vtmn/css-rating): add disabled checkboxes

- packages/sources/css/src/components/forms/text-input/src/index.css
- Move margins from the input to the label and the helper text to avoid useless margins when no label OR/AND helper text
- Text input has default margin even without label and text helper
- Close #946 
- No
> fix(@vtmn/css): change the text input marge holders

- package.json
- packages/showcases/vue/.storybook/preview.js
Storybook docs were not working for `vue`.
Most likely an update that made a piece of code irrelevant. 
In `.storybook/preview.js`
```javascript
export const parameters = {
actions: { argTypesRegex: '^on[A-Z].*' },
backgrounds,
controls: { expanded: true },
viewport: {
viewports,
},
// match condition is always false
docs: {
transformSource(src, ctx) {
const match = /\b("')?template\1:\s*`([^`]+)`/.exec(src);
if (match) {
return templateSourceCode(dedent(match[2]), ctx.args, ctx.argTypes);
}
return src;
},
}
};
```
The `match` condition was always false wich led to undefined argument, that's why storybook was throwing an error 🥳 !
Another small change, i am also using [volta](https://volta.sh/) wich is a replacement for `nvm`, the current pinned version `node@16.3.1` was not working wich …
> docs(@vtmn/vue): fix storybook docs

- packages/showcases/core/csf/components/actions/button.csf.js
- packages/sources/vue/src/components/VtmnButton/VtmnButton.vue
- packages/sources/vue/src/components/VtmnButton/types.ts
Add type and isDisabled props and better Typescript definition with types.
- No
We will still need to update VtmnButton component with VtmnIcon when this component will be ready.
> feat(@vtmn/vue): add types and props to`VtmnButton` component

- packages/sources/vue/src/components/VtmnRadioButton/VtmnRadioButton.vue
Make radio button component reactive and ready to use in a Vue project.
Currently the component can't be use in a Vue form.
- Yes
I removed the 'checked' prop because it's not useful in a Vue context. With this new way to check or not the radio button we ensure the reactive v-model value match with the input value which make more sense in a form. Feel free to reach me if you need more information about this breaking change.
> feat(@vtmn/vue): add reactivity to `VtmnRadioButton` component

- packages/sources/svelte/src/components/VtmnButton.svelte
- packages/sources/svelte/src/components/VtmnLink.svelte
- packages/sources/svelte/src/components/VtmnPopover.svelte
- packages/sources/svelte/src/components/VtmnTextInput.svelte
Refer to #958 
On svelte component (example VtmnButton.svelte), the component import the style on the <script> node.
This type of operation can cause side effects on the generated component on the SSR because is tires to interpret the css as script.
The quick solution is to move the css import into a <style> node.
To go further, during the build, inject the script directly into the component to make it totally autonomous (without node imports)
> fix(@vtmn/svelte): move import style into <style> element

- packages/sources/svelte/package.json
Following the PR #960 it is now possible using a VtmnButton import from `@vtmn/svelte/src/component/VtmnButton.svelte` to import the component.
However, this operation can be cumbersome later on and does not use the compiled files in the `dist` folder.
To remedy this problem, it is necessary to add an `exports` node in the `package.json` file.
This one will have for goal : 
- When using an `import { VtmnButton } from '@vtmn/svelte'` to point the export from `@vtmn/svelte` to the `src/components` folder 
- When exporting `*.svelte` files, to point to those generated in the `dist`folder.
> chore(package): add exports on package.json

- packages/showcases/svelte/stories/components/indicators/VtmnPrice/VtmnPrice.stories.svelte
- packages/sources/svelte/package.json
- packages/sources/svelte/rollup.config.js
- packages/sources/svelte/src/components/index.js
- packages/sources/svelte/src/components/indicators/VtmnPrice/VtmnPrice.svelte
- packages/sources/svelte/src/components/indicators/VtmnPrice/enums.js
Creation of the component VtmnPrice.
The component will accept as props:
- size (default value: `medium`)
- variant (default value: `default`)
Todo list :
> feat(@vtmn/svelte): add price component

- packages/sources/vue/src/components/selection-controls/VtmnCheckbox/VtmnCheckbox.vue
- packages/sources/vue/src/components/selection-controls/VtmnToggle/VtmnToggle.vue
- packages/sources/vue/src/components/selection-controls/VtmnToggle/types.ts
Update `VtmnToggle` and `VtmnCheckbox` components to make them ready to use in a Vue 3 project with reactivity.
Also add `VtmnCheckbox` standalone props to make it useable according to the design system. More explanation in Context section below.
I added a standalone props for `VtmnCheckbox` in order to be able to use it in all the possible context.
You only need this props when you want to display only one checkbox for example accepting or not the general condition in an ecommerce context. In this case we need our component to emit a true or false value and not the value that it would contain that would be pushed in an array when using multiple checkbox.
I know VTMN DS aim to release stateless component but in our case it's not possible to avoid this props and to emit the …
> feat(@vtmn/vue): add `VtmnToggle` and `VtmnCheckbox` reactivity

- packages/sources/css/src/components/forms/select/src/index.css
- packages/sources/css/src/components/forms/text-input/src/index.css
- packages/sources/css/src/components/selection-controls/quantity/src/index.css
- Re add `line-height` for labels and helper-text in forms component
- Move margin holders from the input to the label and helper-text
- Fix some width that were not semantic already
- Some designers found the label and the helper text too narrow with the text input because we removed the line height in a previous pull request, so I put them put to be identical with the design of the components.
- No
> fix(@vtmn/css): change margin holders for quantity and select.

- packages/showcases/css/stories/components/overlays/modal/examples/overview.html
- packages/sources/css/src/components/overlays/modal/src/index.css
- remove `border-radius` for the bottom of the modal on mobile devices
- The overview showcase turns correctly into mobile responsive
- No
> fix(@vtmn/css): modal radius + overview fix

- packages/sources/svelte/package.json
- packages/sources/svelte/src/index.js
This PR fix some issues with svelte build.
- Remove all css on .js files for the SSR rendering
- Thanks to this modification, it is possible to delete in the package.json the exports because no more js file contains css style
- Remove `@vtmn/css-design-token` because is no longer used in the package
> chore(svelte): remove exports + clean css

- packages/showcases/css/stories/components/overlays/tooltip/examples/overview.html
- packages/sources/css/src/components/overlays/tooltip/src/index.css
- packages/sources/css/src/design-tokens/src/shadows.css
- packages/sources/css/src/design-tokens/src/themes/core-dark.css
- packages/sources/css/src/design-tokens/src/themes/core-light.css
- packages/sources/css/src/design-tokens/src/themes/default.css
- Add a `role="tooltip"` and an `aria-describedby` for the tooltip component
- `Primary reversed` goes from `white` to `black` in light theme
- `Primary reversed` goes from `black` to `white` in dark theme
- Design token in dev didin't match the correct value in the [figma file](https://www.figma.com/file/ItP6IOCNwSWlskFgpGw7TU/Vitamin---Core-theme-(Dark-mode)-(v0)?node-id=563%3A531https://www.figma.com/file/ItP6IOCNwSWlskFgpGw7TU/Vitamin---Core-theme-(Dark-mode)-(v0)?node-id=563%3A531)
- Enhance accessibility of the `tooltip`
- No
> refactor(@vtmn/css): add a11y markup + fix bug semantic colors border

- packages/showcases/css/stories/components/indicators/tag/examples/overview.html
- packages/sources/css/src/components/indicators/tag/src/index.css
- Add showcase and a clas to display an icon in a `tag` component
- A tag can be led by an icon to emphasize meaning
- No
> feat(@vtmn/css): add icon leading for tag

- packages/sources/css/src/components/actions/button/src/index.css
- Add `line-height: 1;` for `button` component to have a better alignment with icons
- `primary-reversed` border color changed from `vtmn-semantic-color_border-primary-reversed` to `vtmn-semantic-color_border-primary` 
- No
> fix(@vtmn/css): button line-height + primary-reversed border

- packages/showcases/svelte/stories/components/overlays/VtmnAlert/VtmnAlert.stories.svelte
- packages/sources/svelte/package.json
- packages/sources/svelte/rollup.config.js
- packages/sources/svelte/src/components/index.js
- packages/sources/svelte/src/components/overlays/VtmnAlert/README.md
- packages/sources/svelte/src/components/overlays/VtmnAlert/VtmnAlert.svelte
- packages/sources/svelte/src/components/overlays/VtmnAlert/VtmnAlertItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnAlert/enums.js
- packages/sources/svelte/src/components/overlays/VtmnAlert/test/vtmnAlertItem.spec.js
- packages/sources/svelte/src/components/overlays/VtmnAlert/vtmnAlertStore.js
Create a new `VtmnAlert` component for svelte
How it works :
- VtmnAlert need to be put on the main body of the application.
- VtmnAlertItem are used by the VtmnAlert to display toasts
- A store vtmnAlertStore can be imported everywhere on the application, you can use the function `vtmnAlertStore.send({ title: 'Hello world!' })` to send alert to display
```svelte
vtmnAlertStore.send({
'title': 'This is the title of the alert',
'description': 'Alert are used to draw the users attention to an important information',
'withCloseButton': true,
'variant': 'info',
'aria-labelledby': 'Storybook',
'aria-describedby': args.variant,
});
```
The component wait 8 seconds before display the next alert and so one ...
We need to up all elements on an array. The trick here is to take the first element of …
> feat(@vtmn/svelte): add `VtmnAlert` component

- packages/showcases/core/csf/components/overlays/modal.csf.js
- packages/showcases/svelte/stories/components/overlays/VtmnModal/VtmnModal.stories.svelte
- packages/sources/svelte/package.json
- packages/sources/svelte/rollup.config.js
- packages/sources/svelte/src/components/index.js
- packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
- packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModal.spec.js
- packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModalWithDescription.svelte
- packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModalWithSlots.svelte
Add a new component svelte `VtmnModal`
- Add tests on the component
- Workaround for a css issue (#1039)
- Add `animation` properties set at `true` by default. You can disable the show animation. We have some issues with this one on chrome.
> feat(@vtmn/svelte): add `VtmnModal` component

- packages/showcases/core/csf/components/overlays/snackbar.csf.js
- packages/showcases/svelte/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.svelte
- packages/sources/svelte/package.json
- packages/sources/svelte/rollup.config.js
- packages/sources/svelte/src/components/index.js
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/README.md
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbar.svelte
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbarItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/enum.js
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/test/VtmnSnackbar.spec.js
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/test/VtmnSnackbarWithSlots.svelte
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/vtmnSnackbarStore.js
Add `VtmnSnackbar` component for svelte
How it works :
- VtmnSnackbar need to be put on the main body of the application.
- VtmnSnackbarItem are used by the VtmnSnackbar to display toasts
- A store vtmnSnackbarStore can be imported everywhere on the application, you can use the function `vtmnSnackbarStore.send({ content: 'Hello world!', })` to send toast to diplay
```svelte
vtmnSnackbarStore.send({ 
content: 'Hello world!', 
withCloseButton: true,
action: {
label: 'action',
execute: () => {
console.log('Trigger action');
},
},
});
```
> feat(@vtmn/svelte): add `VtmnSnackbar` component

- packages/sources/svelte/package.json
- packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte
- packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRating.spec.js
Issues have been found on the svelte part : 
- Rating component - replace the attribute name `readOnly` by `readonly` to be more iso
- Price component - `@vtmn/css-price` is missing into package.json
> fix(@vtmn/svelte): rating attribute + css-price import

- packages/showcases/svelte/.storybook/main.js
- packages/showcases/svelte/.storybook/preview.js
- packages/showcases/svelte/package.json
- packages/showcases/svelte/stories/components/overlays/VtmnAlert/VtmnAlert.stories.svelte
- packages/showcases/svelte/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.svelte
- packages/showcases/svelte/stories/components/overlays/VtmnToast/VtmnToast.stories.svelte
- packages/showcases/svelte/stories/components/selection-controls/VtmnChip/VtmnChip.stories.svelte
- packages/sources/svelte/src/components/overlays/VtmnAlert/README.md
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/README.md
- packages/sources/svelte/src/components/overlays/VtmnToast/README.md
- packages/sources/svelte/src/components/selection-controls/VtmnChip/README.md
Add readme-plugin for storybook svelte :  
- Apply by default `11y-dark` theme
- Add README.md Alert / Snackbar / Toast / Chip
> docs(@vtmn/svelte): add readme plugin for storybook

- packages/showcases/svelte/stories/components/indicators/VtmnTag/VtmnTag.stories.svelte
- packages/sources/svelte/src/guidelines/iconography/VtmnIcon/VtmnIcon.svelte
Some enhancement + fix on svelte
- Add a story with tag + icon
- VtmnIcon doesn't apply the size on the style but, with a class with a var. More efficient for the weight of class. (same for the color)
> fix(@vtmn/svelte): apply font-size on class + story tag with icon

- packages/sources/react/src/components/forms/VtmnTextInput/VtmnTextInput.tsx
We pass all the component props to the DOM as we receive it.
Some of them are in boolean type which causes a console warning.
(See the screenshots bellow)
We simply cast all the props as string before passing them to the DOM.
No
> fix(@vtmn/react): bad props type given to DOM in `VtmnTextInput`

- packages/showcases/css/stories/components/overlays/modal/examples/demo.runscript.js
- packages/showcases/css/stories/components/overlays/modal/examples/overview.html
- packages/sources/css/src/components/overlays/modal/src/index.css
- The class `vtmn-modal_content_body--overflow-indicator` and its associated tag
- The overflow indicator is buggy when there are no buttons in the modal, so it has been removed until a correct solution is found
- Yes, you can remove the `<div>` tag associated with the class `vtmn-modal_content_body--overflow-indicator`.
- It won't break your modal if you don't remove it
> fix(@vtmn/css): modal indicator overflow

- packages/sources/react/src/components/actions/VtmnButton/VtmnButton.tsx
- packages/sources/react/src/utils/object.ts
It fixes some bug and handles more cases like empty and null inputs.
Also, it casts to string only booleans and numbers because objects and arrays doesn't need to be casted.
The method wasn't working properly when passing more props to components.
Causing errors/warnings when using @vtmn/react components
- No
Testing in Storybook only was a terrible mistake as it doesn't include our use-case, maybe writing test suite for methods like that would be a good start.
> fix(@vtmn/react): utils method and button component

- packages/sources/react/src/components/forms/VtmnSelect/VtmnSelect.tsx
Omit helperText props in VtmnSelect component
The props interface indicates that the component VtmnSelect could use a helperText props
But in reality, it is not used and as in other components, every props are passed to the DOM
In the case where VtmnSelect consumers pass a helperText, this was causing a DOM error (see screenshot)
- No
> refactor(@vtmn/react): omit `helperText` prop in `VtmnSelect`

- packages/sources/svelte/package.json
Link to #1071
With jest, if we import the `@vtmn/svelte` into a test, he can't find the `index.js` from `./src`.
So we need to specify the main into `package.json`
> feat(@vtmn/svelte): add main into package

- packages/showcases/react/stories/components/overlays/VtmnAlert/VtmnAlert.stories.tsx
- packages/sources/react/src/components/overlays/VtmnAlert/VtmnAlert.tsx
Activate `DemoTemplate` on Storybook for the VtmnAlert component.
Conditional display of close button in VtmnAlert component.
Set `onClick` prop to optional since it isn't given in VtmnAlert overview story.
The DemoTemplate wasn't used at all.
The close button was display even if no onClose callback where given.
The overview story wasn't giving the prop onClose therefore it needed to be optional.
The onClose is now executed on the button click, not the alert click
Otherwise, no real change here
No DemoTemplate, only OverviewTemplate, and also the close button wasn't working because no callback given (Before this PR):
https://streamable.com/75s799
After:
https://streamable.com/2ujq69
> refactor(@vtmn/react): `VtmnAlert` component demo & `onClick` event

- packages/sources/vue/src/components/forms/VtmnSelect/VtmnSelect.vue
- packages/sources/vue/src/components/forms/VtmnSelect/types.ts
Add "disabled" attribute to options props. 
We should be able to have disabled options inside our ```VtmnSelect``` component.
- No
The storybook story of the ```VtmnSelect``` component is still missing. Still trying to find a workaround to better use it with Vue 3 context and to be able to add props and reactivity.
> feat(@vtmn/vue): add disabled attr to ```VtmnSelect``` options

- packages/showcases/svelte/stories/components/structure/VtmnCard/VtmnCard.stories.svelte
- packages/sources/css/src/components/structure/card/src/index.css
Add storybook example for card 
- With tag
- With price
- Fix issue with tag on full-image
Without fix
With fix
> docs(@vtmn/svelte): add card story with price and tag

- packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
- packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModal.spec.js
When we use the `VtmnModal` and want to apply custom style on it, the style are applied on the main container `vtmn-modal` and not the content of the modal `vtmn-modal_content`.
The first level only contains the overlay and the content.
In fact, if we want to apply a custom height to the modal for example : 
Without the fix
```
<style>
.variant-full-screen {
.vtmn-modal-content {
height: 100vh;
}
}
</style>
<VtmnModal class="modal-full-screen" />
```
With the fix 
```
<VtmnModal class="vtmn-h-screen" />
```
> fix(@vtmn/svelte): custom class should be apply on the `VtmnModal` content

- packages/sources/css/src/components/forms/text-input/src/index.css
remove forced line-height on `vtmn-text-input`
There's a useless `line-height: 1` declaration on `vtmn-text-input` (which targets `input` and `textarea` tags)
It has no effect on input tags beside selection visualization...
**With line-height :** 
**Without line-height :** 
...but it shrinks the text of textarea : 
**With line-height :** 
**Without line-height :** 
- No
> feat(@vtmn/css): remove useless textInput line-height

- packages/showcases/core/csf/components/indicators/rating.csf.js
- packages/showcases/svelte/stories/components/indicators/VtmnRating/VtmnRating.stories.svelte
- packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte
- packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRating.spec.js
- packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRatingWithSlots.svelte
Some changes:  
- Remove slots
- `rating` property move to `value`
- slot secondary are moved to `comments` property
- add `showValue` property to display the value string
- rework the storybook
- adapt unit-tests
- New rule for compact rating, if value > 0 fill the star, if value = 0 line
> fix(@vtmn/svelte): rework `VtmnRating` component

- packages/sources/css/src/components/actions/button/src/index.css
use logical properties in for button's icons padding and margin 
Spacing is wrong in a right to left reading context.
**Take this organism :**
**In rtl direction it gives us this :** 
**This PR aims to correct icon spacing :** 
- No
> feat(@vtmn/css): use logical properties in btn spacings

- packages/sources/svelte/src/components/structure/VtmnDivider/VtmnDivider.svelte
When we use the `VtmnDivider` inside an application, when we don't apply a slot, a empty line are display at start for a second.
Don't apply the class if no default slot are defined prevent this side effect.
> fix(@vtmn/svelte): prevent flickering `VtmnDivider`

- packages/showcases/css/stories/components/navigation/breadcrumb/examples/overview.html
- packages/sources/css/src/components/navigation/breadcrumb/src/index.css
- Replace the `aria-label` by `aria-current="page"` to show the current page of the breadcrumb
- `line-height` set to 1 instead of 0;
- Add a11y requirements for the breadcrumb
- No
> feat(@vtmn/css-breadcrumb): add a11y aria-current

- packages/sources/css/src/components/actions/button/src/index.css
For icon-left / icon-right vairants :
- Small button icon goes from `--vtmn-typo_text-3-font-size` to `16px`
- Medium (default) button icon goes from `--vtmn-typo_text-2-font-size` to `20px`
- Small button icon goes from `--vtmn-typo_title-5-font-size` to `24px`
For icon-alone vairants :
- Small button icon goes from `--vtmn-typo_text-3-font-size` to `20px`
- Medium (default) button icon goes from `--vtmn-typo_text-2-font-size` to `24px`
- Small button icon goes from `--vtmn-typo_title-5-font-size` to `32px`
Accessibility:
- `width` turned into `inline-size`
- `height` turned into `block-size` 
- Icon in `buttons` were smaller than in the design library.
- Add a11y on the css sizes
- No
> fix(@vtmn/css): edit `button` icon sizes, increase icon sizes for `icon-alone` variant, a11y 

- packages/sources/css/src/components/selection-controls/quantity/src/index.css
- Add `border: 0` 
- In some browsers, the `quantity` input has a default border, it shouldn't have one.
- No
> feat(@vtmn/css-quantity): no default border

- packages/sources/css/src/components/overlays/modal/src/index.css
- packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
- packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModal.spec.js
Add some changes on the component : 
- Remove the `vtmn-modal_content_body--overflow-indicator` on svelte (PR https://github.com/Decathlon/vitamin-web/pull/1068)
- Add `flex: auto` on title to make the title take all the remaining width.
- Add `flex: auto` on description to make the description content fill all the page. This fix will set the action div always on the bottom of the modal.
- Remove `padding-bottom` not necessary since `vtmn-modal_content_body--overflow-indicator` are removed
> fix(@vtmn/svelte): `VtmnModal` add flex auto + remove overflow indicator

- packages/sources/css/src/components/overlays/modal/src/index.css
Refer to https://github.com/Decathlon/vitamin-web/pull/1143
`flex: auto` must be set on the class `.vtmn-modal_content_body` and not `.vtmn-modal_content_body--text`
> fix(@vtmn/css): move flex auto to body

- packages/sources/css/src/components/overlays/modal/src/index.css
On small device, the scroll bar are under content.
But in some cases, this solution produce side effects.
| Before | After  |
|--------|--------|
| ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-17 at 10 05 05](https://user-images.githubusercontent.com/2856778/168762818-e3a20e1f-8460-4694-8873-28e2dfd8b29c.png)  | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-05-17 at 10 06 07](https://user-images.githubusercontent.com/2856778/168762812-827ad3cd-6862-4760-a919-49c6ce2171f0.png) |
The solution is to export the padding to the mobile component so that the scroll is outside the container
> fix(@vtmn/css): fix scroll padding mobile

- packages/sources/svelte/src/components/overlays/VtmnAlert/vtmnAlertStore.js
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/vtmnSnackbarStore.js
- packages/sources/svelte/src/components/overlays/VtmnToast/vtmnToastStore.js
- packages/sources/svelte/src/utils/math.js
Before : 
- `VtmnOverlays` are generate id by increment a number.
This way wan provide duplicate id in the DOM.
After : 
- Generate uuid and prefix with the component name.
This way prevent all duplicate id in the DOM.
> fix(@vtmn/svelte): move overlay id to uuid

- packages/showcases/svelte/stories/components/navigation/VtmnSearch/VtmnSearch.stories.svelte
- packages/sources/svelte/src/components/navigation/VtmnSearch/VtmnSearch.svelte
- packages/sources/svelte/src/components/navigation/VtmnSearch/test/VtmnSearch.spec.js
Enhancement on the `VtmnSearch`
- Add property `ariaLabels` to defined aria labels on component's elements
- Add condition in order to hide clear button if value are not defined
> fix(@vtmn/svelte): `VtmnSearch` hide clear button if no value

- packages/sources/react/src/components/navigation/VtmnSearch/VtmnSearch.tsx
Button type added on the "clear" button to be able to press enter to submit when the `VtmnSearch` component is used inside a `form` tag.
When `VtmnSearch` is used inside a `form` tag, press "enter" key empty the input and the submit event is not triggered.
It seems like the "clear" button "catch" the enter event and act like it's clicked.
It can be reproduced in the following codesandbox:
https://codesandbox.io/s/vtmnsearch-submit-issue-fsi0f8?file=/src/App.js
Adding a type on the "clear" button fix the issue.
No
> fix(@vtmn/react): `VtmnSearch` 'enter' key inside form tag do not clear input

- packages/sources/react/src/components/navigation/VtmnNavbar/VtmnNavbar.tsx
Looks like we forgot to edit some copy/paste :)
Import @vtmn/css-navbar css rather than @vtmn/css-button one
Component doesn't import dedicated css
- No
> fix(@vtmn/react - Navbar): Import navbar css rather than button one

- packages/sources/css/src/components/selection-controls/quantity/src/index.css
- `quantity` default borders (input + buttons) is similar to the `text-input`'s.
- Change from `rem(2px) var(--vtmn-semantic-color_border-secondary)` to `rem(1px) var(--vtmn-semantic-color_border-inactive)` 
- The `text-input` and the `quantity` component weren't very similar so it causes a lack of homogeneity.
- No
> fix(@vtmn/css): change borders `quantity` component

- packages/sources/css/src/components/structure/card/src/index.css
- Gradient goes from 0% to 100% of the card height instead of 20% to 100%
- The current linear gradient on the `card` component may cause accessibility problems.
- No
> fix(@vtmn/css): linear gradient full image card

- packages/showcases/css/stories/components/indicators/rating/examples/overview.html
- packages/showcases/css/stories/components/indicators/rating/examples/read-only.html
- Removed some `rating` examples with only the number of ratings in parentheses.
- Some ratings examples were not desired because they weren't precise.
- No
> feat(@vtmn/css): remove some ratings showcase examples

- packages/showcases/css/.storybook/preview-head.html
- packages/showcases/icons/.storybook/preview-head.html
- packages/showcases/react/.storybook/preview-head.html
- packages/showcases/svelte/.storybook/preview-head.html
- packages/showcases/vue/.storybook/preview-head.html
- packages/sources/css/presets/tailwind/theme.js
- packages/sources/css/src/components/actions/button/src/index.css
- packages/sources/css/src/components/indicators/badge/src/index.css
- packages/sources/css/src/components/structure/accordion/src/index.css
- packages/sources/css/src/components/structure/divider/src/index.css
- packages/sources/css/src/components/structure/list/src/index.css
- packages/sources/css/src/design-tokens/src/shadows.css
- packages/sources/css/src/design-tokens/src/themes/core-dark.css
- packages/sources/css/src/design-tokens/src/themes/core-light.css
- packages/sources/css/src/design-tokens/src/themes/default.css
```
☀️ Core Theme - Light Mode
Today we’ve got: 
borderPrimary == white
borderSecondary == grey200
borderTertiary == grey100
What we want:
borderPrimary == grey200
borderSecondary == grey100
borderTertiary == white
--
🌙 Core Theme - Dark Mode
Today we’ve got: 
borderPrimary == grey800
borderSecondary == grey700
borderTertiary == black
What we want:
borderPrimary == grey700
borderSecondary == black
borderTertiary == grey800
```
- Some semantics were not logic in their shade order
- Close #1191 
- No
> feat(@vtmn/css): change border colors, add missing colors in color themes

- packages/showcases/react/stories/components/navigation/VtmnSearch/VtmnSearch.stories.tsx
- packages/sources/react/src/components/navigation/VtmnSearch/VtmnSearch.tsx
Allow user to call a function when clicking on clear icon
related to https://github.com/Decathlon/vitamin-web/issues/1197
- No
Had some issues building the project so I couldn't fully test. But the changes are simple enough
> feat(@vtmn/react): add `onClear` prop on `VtmnSearch` component

- packages/sources/css/src/components/actions/dropdown/src/index.css
We realized that there was a problem with the display of the dropdown on iOS (no problem on Android though).
_Originally reported by @rtorond, thanks for this._
- No
> fix(@vtmn/css): `height:auto` in the `<label>` of `VtmnDropdown` component

- packages/sources/svelte/src/components/structure/VtmnDivider/VtmnDivider.svelte
- packages/sources/svelte/src/components/structure/VtmnDivider/test/VtmnDivider.spec.js
This PR fixes two problems on `VtmnDivider` Svelte component.
1. Divider has an empty span on several showcases like this one in `VtmnTabs` _(thanks Christophe Drag for reporting me this)_: https://decathlon.github.io/vitamin-web/@vtmn/showcase-svelte/?path=/story/components-navigation-vtmntabs--overview
2. There is warning when `yarn test` for the `VtmnDivider` component because `labelId` is undefined. That's why I propose to use the `uuid()` function to generate a unique identifier if not present (for a11y purposes).
- No
> fix(@vtmn/svelte): `VtmnDivider` component `labelId` & default `<slot></slot>`

- packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
When `VtmnModal` are open, we apply a `overflow: hidden` on the body.
In fact, this solution works pretty well on desktop, but on mobile devices the touch are always enable and in some cases, the user can scroll over the body in the background.
To prevent this effect, we apply a `touch-action:none` on the body when the modal are open.
> fix(@vtmn/svelte): prevent body scroll on mobile for `VtmnModal`

- packages/sources/css/src/components/forms/select/src/index.css
- Add a `min-inline-size` to 100% to keep the container flexible with the size of the label.
- The helper text is now wrapped if longer than the select container
- The select container arrow could be misplaced if the helper text or the label was longer than the container.
- No
> fix(@vtmn/css): fix min-width and wrap behavior to correctly display the arrow

- packages/sources/svelte/src/components/structure/VtmnDivider/VtmnDivider.svelte
Current : 
Expected : 
No breaking changes.
We check if the default slot are defined
> fix(@vtmn/svelte): fix display label

- .github/workflows/build-canary.yml
- CONTRIBUTING.md
- packages/sources/svelte/package.json
- packages/sources/svelte/rollup.config.js
- yarn.lock
Change the rollup configuration.
Switch to postcss to insert the `@import`ed css into the dist folder.
This enhancement doesn't required anymore the `@vtmn/css-*` as dependencies.
In the dist output with this changes : 
- Add `rollup-plugin-terser` in order to minify the bundle
- Move `rollup-plugin-css-only` to `rollup-plugin-postcss`
> build(@vtmn/svelte): inject CSS to `dist` folder by switching to PostCSS

- packages/sources/react/src/components/structure/VtmnDivider/VtmnDivider.tsx
changed `aria-labelledBy` with `aria-labelledby` in VtmnDivider
`aria-labelledBy` syntax is incorrect.
- No
> fix(@vtmn/react): aria prop typo in `VtmnDivider`

- packages/sources/svelte/src/components/navigation/VtmnSearch/VtmnSearch.svelte
This PR aimed to add an attribute `inputRef` only for svelte.
With this props, we can get the reference of the input from the parent. For example : 
```html
<script>
let vtmnButtonRef;
onMount(() => {
vtmnButtonRef.focus();
});
</script>
<VtmnSearch bind:inputRef={vtmnButtonRef} />
```
> fix(@vtmn/svelte): add export inputRef into the component `VtmnSearch`

- packages/showcases/core/csf/components/forms/text-input.csf.js
- packages/sources/svelte/src/components/forms/VtmnTextInput/VtmnTextInput.svelte
- packages/sources/svelte/src/components/forms/VtmnTextInput/test/VtmnTextInput.spec.js
Added on:input and on:change directives
With the previous implementation, the VtmnTextInput couln't handle a specific action whenever the value changes (on:input) like the native HTML input does.
For example, in my case I couldn't perform validations on the fly whenever the textfield changes
- Add on:input and on:change on theTextInput implementation to inherit the native HTML input behaviour
- Updated the TextInput's Component Story Format to handle these actions
- Added unit test to check if the on:input event is called once on every input change
No
> feat(@vtmn/svelte): add `on:input` and `on:change` on `VtmnTextInput` component

- packages/showcases/core/csf/components/structure/skeleton.csf.js
- packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
- packages/sources/svelte/src/components/structure/VtmnSkeleton/enums.js
- packages/sources/svelte/src/components/structure/VtmnSkeleton/test/vtmnSkeleton.spec.js
Linked to https://github.com/Decathlon/vitamin-web/issues/1249
Add a new input `unit` on `VtmnSkeleton`
Rules applied : 
- Unit = `%` by default
- Width = `100` by default
- If unit are not `['%', 'em', 'rem', 'vw', 'ch', 'px']` -> unit = `%` (default value)
- If width are `< 0` -> width = `100` (default value)
> fix(@vtmn/svelte): add unit param on `VtmnSkeleton`

- packages/sources/svelte/src/components/navigation/VtmnSearch/VtmnSearch.svelte
- packages/sources/svelte/src/components/navigation/VtmnSearch/test/VtmnSearch.spec.js
Fix an issue on the `VtmnSearch`.
Before : 
- `className` export should be set to pass class to the `VtmnSearch` component
Now : 
- `class` inject the component's class to the `VtmnSearch` component
> fix(@vtmn/svelte): class on the `VtmnSearch`

- packages/showcases/css/stories/components/overlays/popover/examples/overview.html
- packages/showcases/svelte/stories/components/overlays/VtmnPopover/VtmnPopover.stories.svelte
- packages/sources/css/src/components/overlays/popover/src/index.css
- packages/sources/react/src/components/overlays/VtmnPopover/VtmnPopover.tsx
- packages/sources/svelte/src/components/overlays/VtmnPopover/VtmnPopover.svelte
- packages/sources/svelte/src/components/overlays/VtmnPopover/test/VtmnPopover.spec.js
- packages/sources/vue/src/components/overlays/VtmnPopover/VtmnPopover.vue
- CSS: clean up popover positioning
- A11y: remove unnecessary attributes, add missing attributes, update values
- Integration: update React / Vue / Svelte components accordingly
- An [issue (#1259)](https://github.com/Decathlon/vitamin-web/issues/1259) has been opened on a weird positioning of the popover in some context.
- The component css had indeed curious positioning values such as absolute positioning dependent on its size (should not), magic number (52%, 40%, ...) and unwanted dependency to other component (VtmnButton).
- The component accessibility attributes was partly inaccurate: was defined as "tooltip" instead of "dialog" (since it is focusable), sometimes triggerred by anchor link in some showcases, missing id and aria attributes, etc.
- No
> fix(@vtmn/css, @vtmn/svelte, @vtmn/react, @vtmn/vue): popover position & a11y (#1259)

- packages/sources/react/src/components/overlays/VtmnAlert/VtmnAlert.tsx
Added an aria-label to the alert component
aria labelling is mandatory on dialog-role elements :
https://dequeuniversity.com/rules/axe/4.4/aria-dialog-name?application=axeAPI
It's missing on VtmnAlert component : 
- No
> fix(@vtmn/react): missing accessible name on VtmnAlert

- packages/showcases/vue/stories/components/selection-controls/VtmnChip/VtmnChip.stories.js
- packages/sources/vue/src/components/selection-controls/VtmnChip/VtmnChip.vue
Fix the close button of the Chip component for Vue.
It was not possible to interact with the input variant of the Chip component in Vue.
- No
> fix(@vtmn/vue): cancel event is not present in `VtmnChip` component (input variant)

- packages/sources/react/src/components/forms/VtmnSelect/VtmnSelect.tsx
- packages/sources/react/src/components/forms/VtmnTextInput/VtmnTextInput.tsx
- packages/sources/react/src/components/selection-controls/VtmnCheckbox/VtmnCheckbox.tsx
- packages/sources/react/src/components/selection-controls/VtmnRadioButton/VtmnRadioButton.tsx
- packages/sources/react/src/components/selection-controls/VtmnToggle/VtmnToggle.tsx
This PR add actual form elements refs in following Vtmn form components :
`VtmnTextInput`, `VtmnSelect`, `VtmnCheckbox`, `VtmnRadioButton` & `VtmnToggle`
_(refs are already forwarded in `VtmnButton` and `VtmnQuantity`)_
The purpose is to be able to access actual form element. 
It allows an easy read/write on those.
[React Hook Form](https://react-hook-form.com/) - which seems like one of the best solution rn in terms of form validation - base its implementation on those
- No
> feat(@vtmn/react): add ref forwarding on form elements

- packages/sources/react/package.json
- packages/sources/svelte/package.json
- packages/sources/vue/package.json
Signed-off-by: Shyrro <zakaria.sahmane@decathlon.com>
Allow treeshaking by adding `sideEffects: false` in `package.json` of every framework. 
This will allow the callers that use modern bundlers (Webpack 5, Vite, Rollup etc), to only import the components they use instead of everything. 
Currently, if we do `import { VtmnAccordion } from '@vtmn/react'` we will only have one big `index.js` in the build, whereas we only need the chunk related to the Accordion and its deps.
It reduces perf issues for all apps. 
Here is an example of Vitamin in a Next 12 app : 
We can see that Vitamin dist only contains an `index.es.js` instead of different chunks of used components like the other modules. This is a small app and and we can see that `@vtmn/react` is taking a lot of space on its own without …
> build: add sideEffects false to allow treeshaking

- packages/showcases/svelte/stories/components/structure/VtmnList/VtmnList.stories.svelte
- packages/showcases/svelte/stories/components/structure/VtmnListItem/VtmnListItem.stories.svelte
- packages/sources/svelte/src/components/actions/VtmnButton/VtmnButton.svelte
- packages/sources/svelte/src/components/structure/VtmnListItem/VtmnListItem.svelte
- packages/sources/svelte/src/components/structure/VtmnListItem/test/VtmnListItem.spec.js
- packages/sources/svelte/src/components/structure/VtmnListItem/test/VtmnListItemWithSlots.svelte
- packages/sources/svelte/src/utils/keyCodes.js
With the last version of `VtmnListItem` we have found some issues with accessibility.
This PR fixed all issue due to keypress / click / stop propagation on children.
For example : 
- `<li>` click action are not possible with keyboard, only mouse.
No breaking changes, just changes on the role by default for `VtmnListItem`
> fix(@vtmn/svelte): fix events accessibility `VtmnListItem`

- packages/sources/svelte/README.md
Closes #1331 :  improve the current documentation of @vtmn/svelte with the preprocess part.
An explanation has been added in the corresponding README.
In #1326 an issue was reported that the use of Vitamin svelte components is not clear, especially on the treatment of the CSS which was reporting errors .
- No
> feat(@vtmn/svelte): add doc on style preprocessing

- packages/sources/react/src/components/overlays/VtmnTooltip/VtmnTooltip.tsx
Use clsx instead of null operator because it was returning undefined. 
As you can see in the followinf snapshot
It brings more clarity in html. We could see sometime undefined and bring questioning.
- No
> feat: use clsx library for className props

- CONTRIBUTING.md
Just fixed a typo inside our `CONTRIBUTING.md` regarding our GitHub board URL.
> docs: fix github board url in contributing file

- packages/showcases/core/csf/components/indicators/price.csf.js
- packages/sources/css/src/components/indicators/price/src/index.css
- packages/sources/react/src/components/indicators/VtmnPrice/VtmnPrice.tsx
- packages/sources/svelte/src/components/indicators/VtmnPrice/VtmnPrice.svelte
- packages/sources/svelte/src/components/indicators/VtmnPrice/test/VtmnPrice.spec.js
- packages/sources/vue/src/components/indicators/VtmnPrice/VtmnPrice.vue
Issue here https://github.com/Decathlon/vitamin-design/issues/167
This PR is for completed this one : https://github.com/Decathlon/vitamin-web/pull/1341
To avoid some breaking changes, we've decided to create a new props called "noPadding" to remove the padding of the Price component.
- No
> feat(@vtmn/css): update price to allow no-padding

- packages/sources/assets/README.md
- packages/sources/assets/package.json
- packages/sources/assets/sprite.svg
- packages/sources/assets/src/scripts/add-sprite-declaration.js
Hello everyone,
We just spent a few hours with the designers of the core team Design System to understand the problem of using sprite with our Vitamin assets (flags, payments, etc.).
In order to resolve it, we need to check all our different flags to remove masks & clip paths manually, and unfortunately, this is huge work & time-consuming which in regard to our team and the different priorities that we have, does not allow us to solve this soon.
That's why we took the decision to postpone the refactoring of all our flags in our next major release in design (@Decathlon/design-system-core-team-design), and so, we decided to no longer support the "sprite" consumption mode for `@vtmn/assets`.
So this PR can close #1313.
Thanks for your understanding.
- No
> refactor(@vtmn/assets): delete sprite consumption mode

- .github/stale.yml
Only configure stale bot for Pull Requests.
- No
> chore(bot): configure stale bot to ignore label "next"

- packages/sources/react/package.json
- packages/sources/react/rollup.config.js
- packages/sources/react/tsconfig.cjs.json
- packages/sources/react/tsconfig.es.json
- packages/sources/react/tsconfig.json
- packages/sources/svelte/package.json
- packages/sources/vue/package.json
Signed-off-by: Shyrro <zakaria.sahmane@decathlon.com>
Removes sourcemap to solve this issue : https://github.com/Decathlon/vitamin-web/issues/1322
Since sourcemaps are mainly for debug purposes, we're also splitting the files to improve treeshake and thus improve debugging capabilities.
It solves two problems : 
- Sourcemaps warnings 
- Improves bundle size ( the fact that sourcemaps are gone makes the package around 200kb lighter, and the fact that it is now treeshakable also makes consumer apps lighter )
- No
> build(@vtmn/react): remove sourcemap and improve treeshaking

- packages/showcases/core/csf/components/selection-controls/quantity.csf.js
- packages/showcases/css/stories/components/selection-controls/quantity/examples/overview.html
- packages/sources/css/src/components/selection-controls/quantity/src/index.css
- packages/sources/react/src/components/selection-controls/VtmnQuantity/VtmnQuantity.tsx
- packages/sources/svelte/src/components/selection-controls/VtmnQuantity/VtmnQuantity.svelte
- packages/sources/vue/src/components/selection-controls/VtmnQuantity/VtmnQuantity.vue
Closes #1356 
As we need to make it extensible without making breaking changes, I propose to add a new prop called `fullWidth` (boolean by default === 'false').
For your information, in Figma, there's no prop (variant) because the behavior is like this: 
- No
> feat: make extensible `Quantity` component

- packages/showcases/core/csf/components/indicators/rating.csf.js
- packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx
- packages/sources/react/src/components/indicators/VtmnRating/utils.ts
- packages/sources/react/src/utils/math.ts
- packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte
- packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRating.spec.js
- packages/sources/svelte/src/components/indicators/VtmnRating/vtmnRating.util.js
- packages/sources/svelte/src/utils/math.js
- packages/sources/vue/src/components/indicators/VtmnRating/VtmnRating.vue
- packages/sources/vue/src/components/indicators/VtmnRating/utils.ts
- packages/sources/vue/src/utils/math.ts
After checking the Decathlon website, I saw many products that the stars are stuck at 4.5.
But some of them are a rating > 4.7.
The rule on the current component is : 
- If my value are a floating value, always round on the 0.5 above.
But here with a value > 4.5 we don't round.
The question here is, what we defined when a number is > 4.5.
I've discuss with @lauthieb, we need to speak about it, maybe take the example of Google that round the value with the nearest one.
And write this rule on the Design System website so that there are no more questions about it.
No breaking changes
This PR aims to enhancer the storybook
- Add conditional values in order to display only specific fields when `readonly` are true / false
| Readonly = false |  Readonly = true |
|---|---|
|<img width="967" …
> fix(@vtmn/svelte, @vtmn/react, @vtmn/vue): fix rounded value on `VtmnRating`

- packages/sources/css/src/components/structure/list/src/index.css
Refer to #1382
With this new behaviour, the user can apply a `vtmn-absolute` in order to manage the text to add ellipsis etc ...
Result : 
No breaking changes
> feat(@vtmn/css): add position relative on `VtmnListItem`

- packages/sources/icons/src/generated/vitamix/font/vitamix.css
Reorder src of vitamix `@font-face`
The browser download and use the first font file supported so the order is important to ensure best performance.
Before is was ttf, woff, woff2 so the browser use the ttf version (62K)
After it's woff2, woff, ttf so it will take the woff2 version which is better (26K, 59% lighter 🚀 )
NB: it's a progressive enhancement, for [oldest](https://caniuse.com/woff2) browsers that doesn't support woff2 nor woff, they will continue to use the ttf version as before
- No
> refactor(vtmn/icons): reorder font src, woff2 in first position for performance

- packages/showcases/core/csf/components/structure/skeleton.csf.js
- packages/showcases/svelte/stories/components/structure/VtmnSkeleton/VtmnSkeleton.stories.svelte
- packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
- packages/sources/svelte/src/components/structure/VtmnSkeleton/enums.js
- packages/sources/svelte/src/components/structure/VtmnSkeleton/test/vtmnSkeleton.spec.js
- packages/sources/svelte/src/utils/style.js
`unit` has non-sense to be managed inside this component, we should instead rely on CSS API instead of managing all possible unit values inside our components. 
If the value is not correct, CSS will manage it its way. 
from `<VtmnSkeleton width="100" />` to `<VtmnSkeleton width="100%" />` or `<VtmnSkeleton width="100px" />`
Also add a `height` parameter which follows this same logic too. 
`<VtmnSkeleton width="100%" height="2em" />`
Note: this should be done in other implementations too (React, Vue)
Closes https://github.com/Decathlon/vitamin-web/issues/1403
- Yes
BREAKING CHANGE: remove `unit` from `VtmnSkeleton`, it should now be passed in the `width` or `height` directly
> feat(@vtmn/svelte): manage height parameter of `VtmnSkeleton` component

- packages/showcases/core/csf/components/structure/skeleton.csf.js
- packages/sources/react/src/components/structure/VtmnSkeleton/VtmnSkeleton.tsx
- packages/sources/vue/src/components/structure/VtmnSkeleton/VtmnSkeleton.vue
`unit` has non-sense to be managed inside this component, we should instead rely on CSS API instead of managing all possible unit values inside our components. 
If the value is not correct, CSS will manage it its way. 
from `<VtmnSkeleton width="100" />` to `<VtmnSkeleton width="100%" />` or `<VtmnSkeleton width="100px" />`
Also add a `height` parameter which follows this same logic too. 
`<VtmnSkeleton width="100%" height="2em" />`
Closes https://github.com/Decathlon/vitamin-web/issues/1403
- Yes
Linked to https://github.com/Decathlon/vitamin-web/pull/1404 (svelte impl)
BREAKING CHANGE: remove `unit` from `VtmnSkeleton`, it should now be passed in the `width` or `height` directly
> feat(@vtmn/react, @vtmn/vue): manage height parameter of `VtmnSkeleton` component

- packages/sources/react/src/components/actions/VtmnDropdown/VtmnDropdown.tsx
Closes #1400 (thanks @jdeca-decat for reporting this)
For your information and to avoid breaking changes for people that already uses `VtmnDropdown`, I didn't spread all the `props` object. I preferred to only pass through the `style` prop.
- No
> fix(@vtmn/react): support style prop for `VtmnDropdown` component

- packages/sources/react/src/components/actions/VtmnLink/VtmnLink.tsx
- packages/sources/react/src/components/navigation/VtmnNavbarLink/VtmnNavbarLink.tsx
- packages/sources/svelte/src/components/actions/VtmnLink/VtmnLink.svelte
- packages/sources/svelte/src/components/actions/VtmnLink/test/VtmnLink.spec.js
- packages/sources/svelte/src/components/navigation/VtmnNavbarLink/VtmnNavbarLink.svelte
- packages/sources/vue/src/components/actions/VtmnLink/VtmnLink.vue
- packages/sources/vue/src/components/navigation/VtmnNavbarLink/VtmnNavbarLink.vue
Compute the rel on the `VtmnLink` and `VtmnNavbarLink` components.
Fix issue with the class on the `VtmnNavbarLink` which can displayed `class="undefined"`
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
- No
> fix(@vtmn/svelte, @vtmn/react, @vtmn/vue): `VtmnNavbarLink` force rel noopener noreferrer if target blank

- packages/sources/react/src/components/indicators/VtmnRating/VtmnRating.tsx
- packages/sources/svelte/src/components/indicators/VtmnRating/VtmnRating.svelte
- packages/sources/svelte/src/components/indicators/VtmnRating/test/VtmnRating.spec.js
- packages/sources/vue/src/components/indicators/VtmnRating/VtmnRating.vue
Closes #1385 
Add on the `VtmnRating` svelte component a check on the restProps in order to not apply it on the root level of the component and under if the rating is interactive.
No changes on the class, only on props like aria-label etc ...
In some case, if the component is interactive, the class are applied twice, on the root level and under.
- No
Tested on svelte / react / vue on storybook.
> fix(@vtmn/svelte, @vtmn/vue, @vtmn/react): interactive `VtmnRating` have duplicate `$$restProps`

- packages/showcases/react/stories/components/forms/VtmnTextInput/VtmnTextInput.stories.tsx
- packages/showcases/svelte/stories/components/forms/VtmnTextInput/VtmnTextInput.stories.svelte
- packages/showcases/vue/stories/components/forms/VtmnTextInput/VtmnTextInput.stories.js
- packages/sources/react/src/components/forms/VtmnTextInput/VtmnTextInput.tsx
- packages/sources/svelte/src/components/forms/VtmnTextInput/VtmnTextInput.svelte
- packages/sources/svelte/src/components/forms/VtmnTextInput/test/VtmnTextInput.spec.js
- packages/sources/svelte/src/components/forms/VtmnTextInput/test/VtmnTextInputSlot.svelte
- packages/sources/vue/src/components/forms/VtmnTextInput/VtmnTextInput.vue
Currently, we only have the ability to have a text as a label in the Input. More often than not, you want to put more things that needs to be customizable ( Optionnal text, tooltip icons etc )
Closes : #1428
Currently, it is impossible to convey more information to the user about the input. One of the most important aspects is the ability to tell if a field is required or not. 
- No
> feat(textinput): add custom label

- packages/sources/css/src/design-tokens/src/breakpoints.css
Change value of Breakpoints design tokens from strings to values to be used in `var()`
[With Web Checkout](https://github.com/dktunited/web-checkout-front/pull/89), we try to rely the most on Vitamin design tokens. But i have an issue when using the breakpoints design tokens. Currently, they are strings and can't be used as value in `var()`
```css
/* Don't work */
--foo: "900px";
max-width: var(--foo);
/* Works */
--foo: 900px;
max-width: var(--foo);
```
If these tokens are used as strings somewhere, it could be a breaking change.
But any others design tokens are values and not strings. I've checked in the codebase any use as strings but didn't found any, so it should not be a problem here
> fix: convert breakpoints variables to values instead of strings

- packages/sources/svelte/src/components/structure/VtmnAccordion/VtmnAccordion.svelte
This is a bugfix to the VtmnAccordion component. The `open` prop was *binded* in the details element.
The previous implementation only allows us to pass the `open` prop down, but changes are not reflected. In particular, we cannot let the parent of the VtmnAccordion know when it is open and when not. So this is just a missing feature, but: there is also a bug in the previous implementation: the line `aria-expanded={open}` means that the `aria-expanded` property is always set to the initial value. It will never be changed.
When the accordion is closed, it does not have the `open` prop and we have `aria-expanded=false`, which is correct:
But when it is opened, the `open` prop is added, **but `aria-expanded=false` stays.**
This pull request fixes this bug.
- No
> fix: make open property of VtmnAccordion reactive

- packages/showcases/react/stories/components/overlays/VtmnAlert/VtmnAlert.stories.tsx
- packages/showcases/svelte/stories/components/overlays/VtmnAlert/VtmnAlert.stories.svelte
- packages/showcases/vue/stories/components/overlays/VtmnAlert/VtmnAlert.stories.js
- packages/sources/react/src/components/overlays/VtmnAlert/VtmnAlert.tsx
- packages/sources/svelte/src/components/index.js
- packages/sources/svelte/src/components/overlays/VtmnAlert/VtmnAlertItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnAlert/test/VtmnAlertItemWithSlots.test.svelte
- packages/sources/svelte/src/components/overlays/VtmnAlert/test/vtmnAlertItem.spec.js
- packages/sources/svelte/src/components/overlays/VtmnAlert/vtmnAlertStore.js
- packages/sources/vue/src/components/overlays/VtmnAlert/VtmnAlert.vue
Svelte part : 
- Export the VtmnAlertItem component in order to be used without the VtmnAlert.
- Title / description can be set with a slot
- Change the `<p>` to `<span>` in order to be ISO with other frameworks
Svelte / React / Vue : 
- Add a new property ariaLabelCloseButton
- Remove the `id` no really necessary
- Set the timeout property to 0 in order to keep the alert visible
Also checked https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/examples/alertdialog/
The div with a role alert doesn't need to have a aria-labelledby /describeby
- Yes
> feat(`@vtmn/svelte`, `@vtmn/react`, `vtmn/vue`): use `VtmnAlert` as a component

- packages/sources/svelte/src/components/selection-controls/VtmnChip/VtmnChip.svelte
Switch the default div element to a `svelte:element` with by default `div` value
Add the restProps inside the component.
In some cases, the VtmnChip can be a link (for apply a filter -> redirect to a new page ...)
Today, if we want to apply a chip with a redirect, we have to wrap it inside a `<a>` tag like that 
```svelte
<a>
<VtmnChip />
</a>
```
But this way introduce a issue with a double focus and a bad semantic (link with a button inside)
So that why I propose to move to a `<svelte:element>
- No breaking changes for the PR :)
> feat(`vtmn/svelte`): change `vtmnChip` in order to set a different type of node

- packages/sources/svelte/src/components/navigation/VtmnBreadcrumb/VtmnBreadcrumb.svelte
- packages/sources/svelte/src/components/navigation/VtmnBreadcrumb/test/VtmnBreadcrumb.spec.js
Add new input in order to set properties on the `<ol>` node.
Missing accessibility properties like `aria-label`
- No
> feat(`@vtmn/svelte`): add property for ol attributes `VtmnBreadcrumb`

- packages/showcases/svelte/.storybook/preview.js
- packages/showcases/svelte/stories/components/overlays/VtmnAlert/VtmnAlert.stories.svelte
- packages/showcases/svelte/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.svelte
- packages/showcases/svelte/stories/components/overlays/VtmnToast/VtmnToast.stories.svelte
- packages/sources/css/src/components/overlays/alert/src/index.css
- packages/sources/css/src/components/overlays/snackbar/src/index.css
- packages/sources/css/src/components/overlays/toast/src/index.css
- packages/sources/css/src/design-tokens/src/animations.css
- packages/sources/svelte/src/components/overlays/VtmnAlert/VtmnAlertItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnAlert/enums.js
- packages/sources/svelte/src/components/overlays/VtmnAlert/test/vtmnAlertItem.spec.js
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbar.svelte
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbarItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/enum.js
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/test/VtmnSnackbar.spec.js
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/vtmnSnackbarStore.js
- packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToastItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnToast/enums.js
- packages/sources/svelte/src/components/overlays/VtmnToast/test/vtmnToastItem.spec.js
- packages/sources/svelte/src/components/overlays/VtmnToast/vtmnToastStore.js
Today the timeout inside the `VtmnAlert` / `VtmnSnackbar` / `VtmnToast` are broken.
Thanks to this fix, it is possible to apply a timeout from 1ms to Infinity on those components without breaking changes !
Fix also an issue with a large text
On NFS it is not possible to apply an alert more than 8s.
- No
> fix(`@vtmn/svelte`, `@vtmn/css`): fix timeout on overlays components

- packages/showcases/core/csf/components/overlays/alert.csf.js
- packages/showcases/core/csf/components/overlays/snackbar.csf.js
- packages/showcases/core/csf/components/overlays/toast.csf.js
- packages/showcases/react/stories/components/overlays/VtmnAlert/VtmnAlert.stories.tsx
- packages/showcases/react/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.tsx
- packages/showcases/react/stories/components/overlays/VtmnToast/VtmnToast.stories.tsx
- packages/showcases/svelte/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.svelte
- packages/showcases/svelte/stories/components/overlays/VtmnToast/VtmnToast.stories.svelte
- packages/showcases/vue/stories/components/overlays/VtmnAlert/VtmnAlert.stories.js
- packages/showcases/vue/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.js
- packages/showcases/vue/stories/components/overlays/VtmnToast/VtmnToast.stories.js
- packages/sources/react/src/components/overlays/VtmnAlert/VtmnAlert.tsx
- packages/sources/react/src/components/overlays/VtmnSnackbar/VtmnSnackbar.tsx
- packages/sources/react/src/components/overlays/VtmnToast/VtmnToast.tsx
- packages/sources/vue/src/components/overlays/VtmnAlert/VtmnAlert.vue
- packages/sources/vue/src/components/overlays/VtmnSnackbar/VtmnSnackbar.vue
- packages/sources/vue/src/components/overlays/VtmnToast/VtmnToast.vue
Refer to https://github.com/Decathlon/vitamin-web/issues/1482
Enhancement of the timeout, it is now possible to set a timeout form 0 to Infinity
Update the `VtmnAlert` / `VtmnSnackbar` / `VtmnToast` on React / Vue in order to match the Svelte logic.
Also update the storybook.
- No
> feat(`@vtmn/react`, `@vtmn/vue`): timeout enhancement

- packages/sources/svelte/src/components/overlays/VtmnAlert/VtmnAlertItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbarItem.svelte
- packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToastItem.svelte
The close dispatch is send even if the user has set a timeout to 0.
This PR fix this behaviour.
- No
> fix(`@vtmn/svelte`): fix dispatch close for `VtmnAlertItem` / `VtmnSnackbarItem` / `VtmnToastItem`

- packages/sources/svelte/src/components/structure/VtmnListItem/VtmnListItem.svelte
- packages/sources/svelte/src/components/structure/VtmnListItem/test/VtmnListItem.spec.js
A non disabled component apply a `tabindex="false"` on the link
https://github.com/Decathlon/vitamin-web/issues/1489
- No
> fix(`@vtmn/svelte`): `VtmnListItem` tabindex can be false
